Purpose: Find out which RNA-seq samples are and aren't yet on SRA.<br>
Author: Anna Pardo<br>
Date initiated: Feb. 9, 2026

In [1]:
import pandas as pd

In [2]:
# load relevant file: rna sample locations
rnaloc = pd.read_csv("./rna_file_locations.csv",sep=",",header="infer")
rnaloc.dropna(axis=0,inplace=True)
rnaloc.head()

                            Directory                 Filename sample_name
0  /labs/Heyduk/gloriosa_RNA/raw_data  Y100_paired_R1.fastq.gz        Y100
1  /labs/Heyduk/gloriosa_RNA/raw_data  Y100_paired_R2.fastq.gz        Y100
2  /labs/Heyduk/gloriosa_RNA/raw_data  Y101_paired_R1.fastq.gz        Y101
3  /labs/Heyduk/gloriosa_RNA/raw_data  Y101_paired_R2.fastq.gz        Y101
4  /labs/Heyduk/gloriosa_RNA/raw_data  Y103_paired_R1.fastq.gz        Y103

In [4]:
# load Yg RNA-seq TPM with metadata (all samples - not just those with over 1 million reads)
mdtpm = pd.read_csv("/home/leviathan22/Yucca_genomics/rna_insilico_genome/TPM/Yg_toYgIS_all_md_TPM_16-Sep-2025.txt",
                   sep="\t",header="infer",usecols=["sample_name","genotype","treat","time","ZT","species"])
mdtpm.head()

/tmp/ipykernel_3942/1019862106.py:2: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  mdtpm = pd.read_csv("/home/leviathan22/Yucca_genomics/rna_insilico_genome/TPM/Yg_toYgIS_all_md_TPM_16-Sep-2025.txt",

   sample_name genotype  time treat    ZT   species
0           Y1       18   1.0     W   1.0  gloriosa
1          Y10      2AB   1.5     W   3.0  gloriosa
2         Y100      2AB   6.5     W  23.0  gloriosa
3  SRR10848707       55   4.0     D  13.0  gloriosa
4  SRR10848820       70   4.0     D  13.0  gloriosa

In [5]:
len(mdtpm.index)

936

In [7]:
# load SRA-to-sample ID sheet
srasamp = pd.read_csv("/home/leviathan22/Yucca_genomics/srr_to_libid.csv",sep=",",header="infer")
srasamp.rename(columns={"libid":"sample_name"},inplace=True)
srasamp.head()

           Run sample_name
0  SRR10663370        Y722
1  SRR10663371        Y723
2  SRR10663372        Y724
3  SRR10663373        Y746
4  SRR10663374        Y721

In [8]:
rnaloc.merge(srasamp)

Empty DataFrame
Columns: [Directory, Filename, sample_name, Run]
Index: []

In [9]:
len(srasamp.index)

395

In [11]:
mdtpm.rename(columns={"sample_name":"Run"}).merge(srasamp)

             Run genotype  time treat    ZT   species     sample_name
0    SRR10848707       55   4.0     D  13.0  gloriosa           Y1000
1    SRR10848820       70   4.0     D  13.0  gloriosa           Y1001
2    SRR10848821       70   3.0     W   9.0  gloriosa           Y1002
3    SRR10848771       61   3.0     W   9.0  gloriosa           Y1003
4    SRR10663905       51   2.0     W   5.0  gloriosa           Y1004
..           ...      ...   ...   ...   ...       ...             ...
367  SRR30854484       53   3.0     W   9.0  gloriosa  gloriosa_53_3W
368  SRR30854485       53   1.0     W   1.0  gloriosa  gloriosa_53_1W
369  SRR30854486       53   6.0     D  21.0  gloriosa  gloriosa_53_6D
370  SRR30854487       53   4.0     D  13.0  gloriosa  gloriosa_53_4D
371  SRR30854488       53   3.0     D   9.0  gloriosa  gloriosa_53_3D

[372 rows x 7 columns]

In [15]:
mdtpm.merge(rnaloc[["sample_name","Directory"]])

,sample_name,genotype,time,treat,ZT,species,Directory
0,Y1,18,1.0,W,1.0,gloriosa,/labs/Heyduk/ygloriosa
1,Y10,2AB,1.5,W,3.0,gloriosa,/labs/Heyduk/gloriosa_RNA/raw_data
2,Y10,2AB,1.5,W,3.0,gloriosa,/labs/Heyduk/gloriosa_RNA/raw_data
3,Y10,2AB,1.5,W,3.0,gloriosa,/labs/Heyduk/ygloriosa
4,Y100,2AB,6.5,W,23.0,gloriosa,/labs/Heyduk/gloriosa_RNA/raw_data
...,...,...,...,...,...,...,...
579,Y97,1AB,1.0,D,1.0,gloriosa,/labs/Heyduk/ygloriosa
580,Y39,1AB,3.0,W,9.0,gloriosa,/labs/Heyduk/ygloriosa
581,Y309,Eudy,1.0,D,1.0,gloriosa,/labs/Heyduk/ygloriosa
582,Y335,Eudy,4.0,D,13.0,gloriosa,/labs/Heyduk/ygloriosa
583,Y293,Eudy,6.0,W,21.0,gloriosa,/labs/Heyduk/ygloriosa

In [13]:
len(rnaloc.index)

753

In [14]:
len(rnaloc["sample_name"].unique())

559