Purpose: Use previously generated BED files for 1kb promoters of all genes in each parental species (*Y. aloifolia* & *Y. filamentosa*) to generate a promoter BED file matching the *in silico Y. gloriosa* chromosome names.<br>
Author: Anna Pardo<br>
Date initiated: Mar. 5, 2026

In [1]:
import pandas as pd

In [23]:
yabed = pd.read_csv("/home/leviathan22/yucca-genomics/Ya_1kb_promoters.bed",sep="\t",header=None)
yfbed = pd.read_csv("/home/leviathan22/yucca-genomics/Yf_1kb_promoters.bed",sep="\t",header=None)

In [24]:
yabed.head()

       0       1       2                     3     4  5
0  Chr01   30807   31807  Yucal.01G000100.v2.1  gene  -
1  Chr01   82673   83673  Yucal.01G000200.v2.1  gene  -
2  Chr01   51110   52110  Yucal.01G000300.v2.1  gene  -
3  Chr01  151105  152105  Yucal.01G000400.v2.1  gene  +
4  Chr01  191562  192562  Yucal.01G000500.v2.1  gene  +

In [22]:
def correct_chroms(bed,sp):
    d = {}
    for i in bed[0].unique():
        d[i] = sp+"_"+i
    bed[0] = bed[0].map(d)
    return bed

In [25]:
yabed = correct_chroms(yabed,"Ya")

In [26]:
yfbed = correct_chroms(yfbed,"Yf")

In [27]:
ygbed = pd.concat([yabed,yfbed])

In [29]:
ygbed.to_csv("/home/leviathan22/yucca-genomics/Yg_1kb_promoters.bed",sep="\t",header=False,index=False)

In [28]:
ygbed.head()

          0       1       2                     3     4  5
0  Ya_Chr01   30807   31807  Yucal.01G000100.v2.1  gene  -
1  Ya_Chr01   82673   83673  Yucal.01G000200.v2.1  gene  -
2  Ya_Chr01   51110   52110  Yucal.01G000300.v2.1  gene  -
3  Ya_Chr01  151105  152105  Yucal.01G000400.v2.1  gene  +
4  Ya_Chr01  191562  192562  Yucal.01G000500.v2.1  gene  +