Purpose: Run Fisher's exact tests for enrichment of CAM genes in maSigPro results (per genotype and per ZT-peak group).<br>
Author: Anna Pardo<br>
Date initiated: Dec. 8, 2025

In [1]:
# load modules
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import statistics
import scipy.stats as stats
import numpy as np
from statsmodels.stats.multitest import fdrcorrection
from venn import venn
from matplotlib.patches import Patch
import json

In [2]:
# load time-structured gene information
cinfo = pd.read_csv("./clusters_ngenes_gt_ztgroup_with36-61-43.txt",sep="\t",header="infer")
cinfo.head()

   cluster genotype  n_CAM_genes  n_all_genes   gtc  ZTpeak
0        1       53          0.0          319  53_1     5.0
1        2       53          1.0          656  53_2    21.0
2        3       53          1.0          882  53_3    17.0
3        4       53          0.0         1071  53_4     9.0
4        5       53          0.0          428  53_5    21.0

In [3]:
cinfo["genotype"].unique()

array(['53', 'Eudy', '13', '52', '48', 'G', '19', '46', '56', '45', '18',
       '70', '1AB', '55', '51', '2AB', '37', 'all', '36', '61', '43'],
      dtype=object)

In [4]:
# remove 'all'
cgt = cinfo[cinfo["genotype"]!="all"]

In [6]:
# load cluster membership info
## annotate whether each gene is CAM (Y/N)
## for which I also need the CAM annotation
cam = pd.read_csv("../degs_downstream/camgenes_Ya_Yf_orthology_synteny.txt",sep="\t",header="infer")

In [11]:
camids = list(cam["GeneID"].unique())

In [35]:
# define a function to load & summarize the data for a given genotype
def load_sum_gt(gt):
    if gt in ["all","gt37"]:
        if gt=="all":
            gtc = pd.read_csv("./hck6_treatonly_"+gt+"_18-Nov.tsv",sep="\t",header="infer")
        else:
            gtc = pd.read_csv("./hck6_treatonly_"+gt+"_17-Nov.tsv",sep="\t",header="infer")
            gt = "37"
    else:
        gtc = pd.read_csv("./Yg"+gt+"_hclust_k6_clusters.txt",sep="\t",header="infer")
        
    gtc["genotype"] = gt
    # set up a CAM column
    camornot = []
    for i in gtc["GeneID"]:
        if i in camids:
            camornot.append("Y")
        else:
            camornot.append("N")
    gtc["CAM_notCAM"] = camornot
    
    # set up a subgenome column
    sg = []
    for i in gtc["GeneID"]:
        if i.startswith("Yucal"):
            sg.append("Ya")
        else:
            sg.append("Yf")
    gtc["subgenome"] = sg
    
    return gtc

In [36]:
dflist = []
for f in os.listdir("./"):
    if(f.endswith("clusters.txt") and f.startswith("Yg")):
        print(f)
        gt = f.split("_")[0].lstrip("Yg")
        print(gt)
        dflist.append(load_sum_gt(gt))

YgG_hclust_k6_clusters.txt
G
YgEudy_hclust_k6_clusters.txt
Eudy
Yg36_hclust_k6_clusters.txt
36
Yg43_hclust_k6_clusters.txt
43
Yg13_hclust_k6_clusters.txt
13
Yg45_hclust_k6_clusters.txt
45
Yg19_hclust_k6_clusters.txt
19
Yg51_hclust_k6_clusters.txt
51
Yg2AB_hclust_k6_clusters.txt
2AB
Yg52_hclust_k6_clusters.txt
52
Yg46_hclust_k6_clusters.txt
46
Yg70_hclust_k6_clusters.txt
70
Yg48_hclust_k6_clusters.txt
48
Yg55_hclust_k6_clusters.txt
55
Yg18_hclust_k6_clusters.txt
18
Yg61_hclust_k6_clusters.txt
61
Yg53_hclust_k6_clusters.txt
53
Yg56_hclust_k6_clusters.txt
56
Yg1AB_hclust_k6_clusters.txt
1AB

In [37]:
dflist.append(load_sum_gt("gt37"))

In [38]:
allclusters = pd.concat(dflist)

In [39]:
allclusters["genotype"].unique()

array(['G', 'Eudy', '36', '43', '13', '45', '19', '51', '2AB', '52', '46',
       '70', '48', '55', '18', '61', '53', '56', '1AB', '37'],
      dtype=object)

In [40]:
set(allclusters["genotype"].unique()).difference(set(cgt["genotype"].unique()))

set()

In [41]:
allclusters.head()

   cluster                GeneID genotype CAM_notCAM subgenome
0        1  Yucal.01G003400.v2.1        G          N        Ya
1        1  Yucal.01G004800.v2.1        G          N        Ya
2        2  Yucal.01G004900.v2.1        G          N        Ya
3        3  Yucal.01G005300.v2.1        G          N        Ya
4        4  Yucal.01G012100.v2.1        G          N        Ya

# Run enrichment of CAM genes for each cluster
(both for each subgenome individually and both together)<br>
also: enrichment of subgenomes in clusters

In [42]:
# create some columns indicating cluster_genotype, cluster_subgenome, genotype_subgenome, and cluster_genotype_subgenome
allclusters["genotype_cluster"] = allclusters["genotype"]+"_"+allclusters["cluster"].astype(str)
allclusters["genotype_subgenome"] = allclusters["genotype"]+"_"+allclusters["subgenome"]
allclusters["genotype_cluster_subgenome"] = allclusters["genotype_cluster"]+"_"+allclusters["subgenome"]
allclusters["cluster_subgenome"] = allclusters["cluster"].astype(str)+"_"+allclusters["subgenome"]

In [43]:
allclusters.head()

,cluster,GeneID,genotype,CAM_notCAM,subgenome,genotype_cluster,genotype_subgenome,genotype_cluster_subgenome,cluster_subgenome
0,1,Yucal.01G003400.v2.1,G,N,Ya,G_1,G_Ya,G_1_Ya,1_Ya
1,1,Yucal.01G004800.v2.1,G,N,Ya,G_1,G_Ya,G_1_Ya,1_Ya
2,2,Yucal.01G004900.v2.1,G,N,Ya,G_2,G_Ya,G_2_Ya,2_Ya
3,3,Yucal.01G005300.v2.1,G,N,Ya,G_3,G_Ya,G_3_Ya,3_Ya
4,4,Yucal.01G012100.v2.1,G,N,Ya,G_4,G_Ya,G_4_Ya,4_Ya

In [45]:
# load TPM data
mdtpm = pd.read_csv("../TPM/Yg_toYgIS_allTPM_correctedmd_over1mil.txt",sep="\t",header="infer")
mdtpm.head()

/tmp/ipykernel_140/3237519056.py:2: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  mdtpm = pd.read_csv("../TPM/Yg_toYgIS_allTPM_correctedmd_over1mil.txt",sep="\t",header="infer")

,sample_name,genotype,time,treat,ZT,species,Yucal.01G000100.v2.1,Yucal.01G000200.v2.1,Yucal.01G000300.v2.1,Yucal.01G000400.v2.1,...,YufilH1095122m.g,YufilH1095123m.g,YufilH1095125m.g,YufilH1095126m.g,YufilH1095128m.g,YufilH1095131m.g,YufilH1095132m.g,YufilH1095134m.g,YufilH1095146m.g,YufilH1095147m.g
0,Y1,18,1.0,W,1.0,gloriosa,34.002815,4.546167,0.0,17.236119,...,0.000000,6.167441,1.435253,0.279077,11.420139,0.662252,1.886709,6.675105,0.0,0.000000
1,Y10,2AB,1.5,W,3.0,gloriosa,40.070758,3.628454,0.0,14.918115,...,0.713535,2.197522,15.695904,1.193256,10.172780,0.000000,2.214483,12.125756,0.0,0.000000
2,Y100,2AB,6.5,W,23.0,gloriosa,47.402599,5.201760,0.0,17.406497,...,0.314746,2.261806,21.742515,1.798380,10.256681,1.748663,2.075757,25.215640,0.0,1.838780
3,Y101,2AB,1.0,D,1.0,gloriosa,57.062380,6.374324,0.0,10.567561,...,0.000000,1.072366,27.573939,1.164591,9.105769,1.257431,2.431447,4.508369,0.0,0.813682
4,Y103,2AB,1.0,D,1.0,gloriosa,34.679279,6.087451,0.0,11.115252,...,0.000000,0.914550,28.621412,0.869052,7.076224,0.515567,2.419222,4.625880,0.0,0.867418

In [131]:
mdtpm["genotype"] = mdtpm["genotype"].astype(str)
mdtpm["genotype"].unique()

array(['18', '2AB', '1AB', '19', '15', 'Eudy', 'G', '56', '36', '13',
       '45', '52', '43', '37', '48', '55', '70', '61', '51', '46', '53',
       '16', '6', '12', '20', '50'], dtype=object)

In [133]:
# subset by genotype (actually used in maSigPro) and ZT (every 4 hours)
zttpm = mdtpm[mdtpm["ZT"].isin([1.0,5.0,9.0,13.0,17.0,21.0])]
zttpm = zttpm[~zttpm["genotype"].isin(["15","6","16","20","12","50"])]

In [134]:
# wrangle tpm data
ttpm = zttpm.set_index("sample_name").drop(["genotype","time","treat","ZT","species"],axis=1).transpose().reset_index().rename(columns={"index":"GeneID"})
ttpm.head()

sample_name,GeneID,Y1,Y101,Y103,Y104,Y105,Y111,Y114,Y116,Y118,...,SRR30854480,SRR30854481,SRR30854482,SRR30854483,SRR30854484,SRR30854485,SRR30854486,SRR30854487,SRR30854488,Y220
0,Yucal.01G000100.v2.1,34.002815,57.062380,34.679279,54.385723,47.391406,48.380647,29.091548,48.429106,35.309049,...,29.891980,27.783417,26.418632,8.504887,20.520463,24.736257,31.956674,26.805637,19.047141,39.036834
1,Yucal.01G000200.v2.1,4.546167,6.374324,6.087451,5.745473,8.458668,6.981615,3.380652,0.853778,3.546558,...,8.703255,9.056956,10.153252,5.971645,11.111843,9.005069,11.949618,10.381398,10.274897,3.534831
2,Yucal.01G000300.v2.1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.165487
3,Yucal.01G000400.v2.1,17.236119,10.567561,11.115252,17.707487,15.536940,19.211534,14.006046,18.419335,7.943992,...,16.551473,16.905682,14.693080,8.349755,13.195929,21.114249,15.557701,11.593198,13.047818,7.751035
4,Yucal.01G000500.v2.1,3.410517,3.129243,3.199743,1.184130,2.099474,3.029870,3.715974,3.284619,1.989776,...,2.349671,2.758449,3.270031,1.936751,3.382665,2.365732,3.914654,3.487815,3.345973,3.059789

In [135]:
yatpm = ttpm[ttpm["GeneID"].isin([i for i in list(ttpm["GeneID"].unique()) if i.startswith("Yucal")])]
yftpm = ttpm[ttpm["GeneID"].isin([i for i in list(ttpm["GeneID"].unique()) if i.startswith("Yufil")])]

In [47]:
# set up some useful functions for Fisher's exact test
## Fisher table setup: isPathway, isGroup
def data_setup(pathwaygenes,groupgenes,path,detype,tpmdf=ttpm):
    pathornot = []
    groupornot = []
    for g in list(tpmdf["GeneID"].unique()):
        if g in pathwaygenes:
            pathornot.append("Yes")
        else:
            pathornot.append("No")
        if g in groupgenes:
            groupornot.append("Yes")
        else:
            groupornot.append("No")
    df = pd.DataFrame(list(zip(list(tpmdf["GeneID"].unique()),pathornot,degornot)),columns=["GeneID","is"+path,"is"+detype])
    return df

In [48]:
allclusters.head()

,cluster,GeneID,genotype,CAM_notCAM,subgenome,genotype_cluster,genotype_subgenome,genotype_cluster_subgenome,cluster_subgenome
0,1,Yucal.01G003400.v2.1,G,N,Ya,G_1,G_Ya,G_1_Ya,1_Ya
1,1,Yucal.01G004800.v2.1,G,N,Ya,G_1,G_Ya,G_1_Ya,1_Ya
2,2,Yucal.01G004900.v2.1,G,N,Ya,G_2,G_Ya,G_2_Ya,2_Ya
3,3,Yucal.01G005300.v2.1,G,N,Ya,G_3,G_Ya,G_3_Ya,3_Ya
4,4,Yucal.01G012100.v2.1,G,N,Ya,G_4,G_Ya,G_4_Ya,4_Ya

In [49]:
cinfo.head()

   cluster genotype  n_CAM_genes  n_all_genes   gtc  ZTpeak
0        1       53          0.0          319  53_1     5.0
1        2       53          1.0          656  53_2    21.0
2        3       53          1.0          882  53_3    17.0
3        4       53          0.0         1071  53_4     9.0
4        5       53          0.0          428  53_5    21.0

In [50]:
allclusters = allclusters.merge(cinfo[["gtc","ZTpeak"]].rename(columns={"gtc":"genotype_cluster"}))
allclusters.head()

,cluster,GeneID,genotype,CAM_notCAM,subgenome,genotype_cluster,genotype_subgenome,genotype_cluster_subgenome,cluster_subgenome,ZTpeak
0,1,Yucal.01G003400.v2.1,G,N,Ya,G_1,G_Ya,G_1_Ya,1_Ya,1.0
1,1,Yucal.01G004800.v2.1,G,N,Ya,G_1,G_Ya,G_1_Ya,1_Ya,1.0
2,1,Yucal.01G014900.v2.1,G,N,Ya,G_1,G_Ya,G_1_Ya,1_Ya,1.0
3,1,Yucal.01G020100.v2.1,G,N,Ya,G_1,G_Ya,G_1_Ya,1_Ya,1.0
4,1,Yucal.01G024300.v2.1,G,N,Ya,G_1,G_Ya,G_1_Ya,1_Ya,1.0

In [62]:
# make a ZTpeak_subgenome column
allclusters["ZTpeak_subgenome"] = allclusters["ZTpeak"].astype(str)+"_"+allclusters["subgenome"]
allclusters.head()

,cluster,GeneID,genotype,CAM_notCAM,subgenome,genotype_cluster,genotype_subgenome,genotype_cluster_subgenome,cluster_subgenome,ZTpeak,ZTpeak_subgenome
0,1,Yucal.01G003400.v2.1,G,N,Ya,G_1,G_Ya,G_1_Ya,1_Ya,1.0,1.0_Ya
1,1,Yucal.01G004800.v2.1,G,N,Ya,G_1,G_Ya,G_1_Ya,1_Ya,1.0,1.0_Ya
2,1,Yucal.01G014900.v2.1,G,N,Ya,G_1,G_Ya,G_1_Ya,1_Ya,1.0,1.0_Ya
3,1,Yucal.01G020100.v2.1,G,N,Ya,G_1,G_Ya,G_1_Ya,1_Ya,1.0,1.0_Ya
4,1,Yucal.01G024300.v2.1,G,N,Ya,G_1,G_Ya,G_1_Ya,1_Ya,1.0,1.0_Ya

In [100]:
# convert ZTpeak column to str
allclusters["ZTpeak"] = allclusters["ZTpeak"].astype(str)

In [66]:
# add subgenome column to CAM annotation
sg = []
for i in list(cam["GeneID"]):
    if i.startswith("Yucal"):
        sg.append("Ya")
    else:
        sg.append("Yf")
cam["subgenome"] = sg
cam.head()

,GeneID,Orthogroup,Pathway,gene_name,gene_abbr,gene_abbr_unique,subgenome
0,Yucal.01G165600.v2.1,OG0001578,CAM-dark,beta-carbonic anhydrase,bCA1234,Ya_bCA1234_1,Ya
1,Yucal.02G112700.v2.1,OG0001578,CAM-dark,beta-carbonic anhydrase,bCA1234,Ya_bCA1234_2,Ya
2,Yucal.04G001000.v2.1,OG0004406,CAM-dark,beta-carbonic anhydrase,bCA5,Ya_bCA5_1,Ya
3,Yucal.07G000800.v2.1,OG0004406,CAM-dark,beta-carbonic anhydrase,bCA5,Ya_bCA5_2,Ya
4,Yucal.03G120900.v2.1,OG0002899,CAM-dark,NAD-dependent malate dehydrogenase (chloroplas...,NAD-MDH-cp,Ya_NAD-MDH-cp_1,Ya

In [72]:
# set up dict of TPM dataframes based on subgenome
tpmdict = {"all":ttpm,"Ya":yatpm,"Yf":yftpm}

In [101]:
def run_fisher(pathway,groupname,pathdf=cam,groupdf=allclusters):
    # get list of genes in cluster
    if "_" in groupname:
        l = len(groupname.split("_"))
        if l==3:
            gdf = allclusters[allclusters["genotype_cluster_subgenome"]==groupname]
        elif l==2:
            if groupname in list(allclusters["genotype_cluster"].unique()):
                gdf = allclusters[allclusters["genotype_cluster"]==groupname]
            elif groupname in list(allclusters["genotype_subgenome"].unique()):
                gdf = allclusters[allclusters["genotype_subgenome"]==groupname]
            elif groupname in list(allclusters["cluster_subgenome"].unique()):
                gdf = allclusters[allclusters["cluster_subgenome"]==groupname]
            elif groupname in list(allclusters["ZTpeak_subgenome"].unique()):
                gdf = allclusters[allclusters["ZTpeak_subgenome"]==groupname]
    elif groupname=="all":
        gdf = allclusters.copy()
    else:
        if type(groupname)==int:
            gdf = allclusters[allclusters["cluster"]==groupname]
        elif "." in groupname:
            gdf = allclusters[allclusters["ZTpeak"]==groupname]
        elif groupname.startswith("Y"):
            gdf = allclusters[allclusters["subgenome"]==groupname]
        else:
            gdf = allclusters[allclusters["genotype"]==groupname]
            
    groupgenes = list(gdf["GeneID"].unique())
        
    # pull out pathway genes
    if "Ya" in groupname:
        pathdf = pathdf[pathdf["subgenome"]=="Ya"]
    elif "Yf" in groupname:
        pathdf = pathdf[pathdf["subgenome"]=="Yf"]
    else:
        pathdf = pathdf
        
    if pathway=="CAM":
        pathlist = ["CAM-dark","CAM-light"]
        pathgenes = list(pathdf[pathdf["Pathway"].isin(pathlist)]["GeneID"].unique())
    else:
        pathgenes = list(pathdf[pathdf["Pathway"]==pathway]["GeneID"].unique())
        
    # set TPM dataframe
    if "Ya" in groupname:
        tpmdf = yatpm
    elif "Yf" in groupname:
        tpmdf = yftpm
    else:
        tpmdf = ttpm
        
    df = data_setup(pathgenes,groupgenes,pathway,groupname,tpmdf)
    #print(df.head())
    data = pd.crosstab(index=df["is"+pathway],columns=df["is"+groupname])
    print(data)
    odds_ratio, p_value = stats.fisher_exact(data)
    return [odds_ratio,p_value]

In [89]:
# define a function to do this for all enrichments in a given set
def test_enrichment(enrichlist,pathway,pathdf=cam,groupdf=allclusters):
    resdict = {"Group":[],"P-value":[],"Odds Ratio":[]}
    for i in enrichlist:
        pvo = run_fisher(pathway,i,pathdf,groupdf)
        resdict['Group'].append(i)
        resdict['Odds Ratio'].append(pvo[0])
        resdict['P-value'].append(pvo[1])
    #pvals = [run_fisher(pathway,i,pathdf,groupdf)[1] for i in enrichlist]
    #odds = [run_fisher(pathway,i,pathdf,groupdf)[0] for i in enrichlist]
    #res = pd.DataFrame(list(zip(enrichlist,pvals,odds)),columns=["Group","P-value","Odds Ratio"])
    res = pd.DataFrame(resdict)
    res["P-adj"] = fdrcorrection(res["P-value"])[1]
    return res

In [136]:
# create some lists of groups to test (one list?)
gtlist = list(allclusters["genotype"].unique())+list(allclusters["genotype_subgenome"].unique())

In [137]:
# subgenome/all list
sg = ["Ya","Yf","all"]

In [138]:
# genotype_cluster combinations (each & both subgenomes)
gtclist = list(allclusters["genotype_cluster"].unique())+list(allclusters["genotype_cluster_subgenome"].unique())

In [139]:
# ZT-peaks (each & both subgenomes)
ztplist = list(allclusters["ZTpeak"].unique())+list(allclusters["ZTpeak_subgenome"].unique())

In [140]:
# stick everyone together
allgroups = sg+gtlist+gtclist+ztplist

In [141]:
len(allgroups)

441

In [142]:
sg

['Ya', 'Yf', 'all']

In [143]:
# run through 'sg'
sgres = test_enrichment(sg,"CAM")

isYa     No    Yes
isCAM
No     8664  34746
Yes       0     40
isYf     No    Yes
isCAM
No     8196  34286
Yes       3     27
isall     No    Yes
isCAM
No     16860  69032
Yes        3     67

In [144]:
sgres

  Group   P-value  Odds Ratio     P-adj
0    Ya  0.000217         inf  0.000613
1    Yf  0.250692    2.151432  0.250692
2   all  0.000408    5.454572  0.000613

In [145]:
# run through genotypes
gtres = test_enrichment(gtlist,"CAM")

isG       No   Yes
isCAM
No     82121  3771
Yes       58    12
isEudy     No   Yes
isCAM
No      77028  8864
Yes        63     7
is36      No    Yes
isCAM
No     59744  26148
Yes       39     31
is43      No    Yes
isCAM
No     47604  38288
Yes       32     38
is13      No   Yes
isCAM
No     82011  3881
Yes       61     9
is45      No    Yes
isCAM
No     69808  16084
Yes       48     22
is19      No    Yes
isCAM
No     74877  11015
Yes       57     13
is51      No    Yes
isCAM
No     43705  42187
Yes       27     43
is2AB     No    Yes
isCAM
No     53481  32411
Yes       26     44
is52      No   Yes
isCAM
No     79723  6169
Yes       61     9
is46      No    Yes
isCAM
No     74526  11366
Yes       56     14
is70      No    Yes
isCAM
No     63254  22638
Yes       41     29
is48      No   Yes
isCAM
No     78940  6952
Yes       59    11
is55      No    Yes
isCAM
No     54030  31862
Yes       34     36
is18      No    Yes
isCAM
No     61794  24098
Yes       42     28
is61      No    Yes
isCAM
No     59561  26331
Yes       30     40
is53      No   Yes
isCAM
No     81761  4131
Yes       68     2
is56      No    Yes
isCAM
No     72910  12982
Yes       50     20
is1AB     No    Yes
isCAM
No     66660  19232
Yes       37     33
is37      No    Yes
isCAM
No     39358  46534
Yes       21     49
isG_Ya     No   Yes
isCAM
No      41435  1975
Yes        32     8
isG_Yf     No   Yes
isCAM
No      40686  1796
Yes        26     4
isEudy_Ya     No   Yes
isCAM
No         38833  4577
Yes           34     6
isEudy_Yf     No   Yes
isCAM
No         38195  4287
Yes           29     1
is36_Ya     No    Yes
isCAM
No       30050  13360
Yes         19     21
is36_Yf     No    Yes
isCAM
No       29694  12788
Yes         20     10
is43_Ya     No    Yes
isCAM
No       23993  19417
Yes         15     25
is43_Yf     No    Yes
isCAM
No       23611  18871
Yes         17     13
is13_Ya     No   Yes
isCAM
No       41433  1977
Yes         34     6
is13_Yf     No   Yes
isCAM
No       40578  1904
Yes         27     3
is45_Ya     No   Yes
isCAM
No       35089  8321
Yes         25    15
is45_Yf     No   Yes
isCAM
No       34719  7763
Yes         23     7
is19_Ya     No   Yes
isCAM
No       37660  5750
Yes         33     7
is19_Yf     No   Yes
isCAM
No       37217  5265
Yes         24     6
is51_Ya     No    Yes
isCAM
No       21770  21640
Yes         15     25
is51_Yf     No    Yes
isCAM
No       21935  20547
Yes         12     18
is2AB_Ya     No    Yes
isCAM
No        26739  16671
Yes          14     26
is2AB_Yf     No    Yes
isCAM
No        26742  15740
Yes          12     18
is52_Ya     No   Yes
isCAM
No       40255  3155
Yes         33     7
is52_Yf     No   Yes
isCAM
No       39468  3014
Yes         28     2
is46_Ya     No   Yes
isCAM
No       37560  5850
Yes         30    10
is46_Yf     No   Yes
isCAM
No       36966  5516
Yes         26     4
is70_Ya     No    Yes
isCAM
No       31980  11430
Yes         21     19
is70_Yf     No    Yes
isCAM
No       31274  11208
Yes         20     10
is48_Ya     No   Yes
isCAM
No       39903  3507
Yes         32     8
is48_Yf     No   Yes
isCAM
No       39037  3445
Yes         27     3
is55_Ya     No    Yes
isCAM
No       26850  16560
Yes         15     25
is55_Yf     No    Yes
isCAM
No       27180  15302
Yes         19     11
is18_Ya     No    Yes
isCAM
No       31070  12340
Yes         23     17
is18_Yf     No    Yes
isCAM
No       30724  11758
Yes         19     11
is61_Ya     No    Yes
isCAM
No       30013  13397
Yes         12     28
is61_Yf     No    Yes
isCAM
No       29548  12934
Yes         18     12
is53_Ya     No   Yes
isCAM
No       41313  2097
Yes         38     2
is53_Yf     No   Yes
isCAM
No       40448  2034
Yes         30     0
is56_Ya     No   Yes
isCAM
No       36657  6753
Yes         29    11
is56_Yf     No   Yes
isCAM
No       36253  6229
Yes         21     9
is1AB_Ya     No   Yes
isCAM
No        33465  9945
Yes          21    19
is1AB_Yf     No   Yes
isCAM
No        33195  9287
Yes          16    14
is37_Ya     No    Yes
isCAM
No       19809  23601
Yes          9     31
is37_Yf     No    Yes
isCAM
No       19549  22933
Yes         12     18

In [94]:
gtres[gtres["P-adj"]<0.05]

     Group       P-value  Odds Ratio     P-adj
0        G  5.113546e-05    4.505583  0.000614
2       36  1.850985e-02    1.816155  0.046275
4       13  4.237065e-03    3.117749  0.018159
5       45  1.302183e-02    1.989265  0.036732
8      2AB  3.204128e-05    2.792457  0.000481
11      70  6.263404e-03    1.976351  0.023488
13      55  1.800725e-02    1.795500  0.046275
15      61  5.780650e-06    3.016014  0.000116
17      56  3.864996e-03    2.246495  0.017838
18     1AB  4.811459e-06    3.091385  0.000116
19      37  8.090141e-03    1.973510  0.026967
20    G_Ya  3.858391e-04    5.244937  0.003858
24   36_Ya  5.285763e-03    2.486015  0.021143
28   13_Ya  9.086256e-03    3.698384  0.028693
30   45_Ya  7.382506e-03    2.530153  0.026056
36  2AB_Ya  8.928607e-04    2.978714  0.007034
37  2AB_Yf  1.289620e-02    2.548475  0.036732
42   70_Ya  3.826409e-03    2.531434  0.017838
44   48_Ya  1.346838e-02    2.844525  0.036732
46   55_Ya  2.834022e-03    2.702295  0.017115
50   61_Ya  4.167731e-07    5.227315  0.000025
56  1AB_Ya  9.378808e-04    3.044531  0.007034
57  1AB_Yf  2.852568e-03    3.127557  0.017115
58   37_Ya  3.731162e-03    2.891022  0.017838

In [146]:
# run through individual clusters (genotype-cluster)
gtcres = test_enrichment(gtclist,"CAM")

isG_1     No  Yes
isCAM
No     84918  974
Yes       65    5
isG_2     No  Yes
isCAM
No     84982  910
Yes       66    4
isG_3     No  Yes
isCAM
No     85351  541
Yes       69    1
isG_4     No  Yes
isCAM
No     85270  622
Yes       70    0
isG_5     No  Yes
isCAM
No     85739  153
Yes       70    0
isG_6     No  Yes
isCAM
No     85321  571
Yes       68    2
isEudy_1     No   Yes
isCAM
No        84096  1796
Yes          70     0
isEudy_2     No   Yes
isCAM
No        84238  1654
Yes          69     1
isEudy_3     No   Yes
isCAM
No        84664  1228
Yes          69     1
isEudy_4     No   Yes
isCAM
No        83501  2391
Yes          66     4
isEudy_5     No  Yes
isCAM
No        84917  975
Yes          69    1
isEudy_6     No  Yes
isCAM
No        85072  820
Yes          70    0
is36_1     No   Yes
isCAM
No      78353  7539
Yes        56    14
is36_2     No   Yes
isCAM
No      80536  5356
Yes        65     5
is36_3     No   Yes
isCAM
No      83374  2518
Yes        70     0
is36_4     No   Yes
isCAM
No      81773  4119
Yes        65     5
is36_5     No   Yes
isCAM
No      83405  2487
Yes        69     1
is36_6     No   Yes
isCAM
No      81763  4129
Yes        64     6
is43_1     No   Yes
isCAM
No      82581  3311
Yes        67     3
is43_2     No   Yes
isCAM
No      77953  7939
Yes        67     3
is43_3     No    Yes
isCAM
No      74828  11064
Yes        64      6
is43_4     No   Yes
isCAM
No      80171  5721
Yes        60    10
is43_5     No   Yes
isCAM
No      79607  6285
Yes        61     9
is43_6     No   Yes
isCAM
No      81924  3968
Yes        63     7
is13_1     No  Yes
isCAM
No      84991  901
Yes        69    1
is13_2     No  Yes
isCAM
No      85100  792
Yes        65    5
is13_3     No  Yes
isCAM
No      85216  676
Yes        70    0
is13_4     No   Yes
isCAM
No      84869  1023
Yes        67     3
is13_5     No  Yes
isCAM
No      85683  209
Yes        70    0
is13_6     No  Yes
isCAM
No      85612  280
Yes        70    0
is45_1     No   Yes
isCAM
No      84108  1784
Yes        64     6
is45_2     No   Yes
isCAM
No      82015  3877
Yes        63     7
is45_3     No   Yes
isCAM
No      84350  1542
Yes        70     0
is45_4     No   Yes
isCAM
No      82522  3370
Yes        65     5
is45_5     No   Yes
isCAM
No      84100  1792
Yes        67     3
is45_6     No   Yes
isCAM
No      82173  3719
Yes        69     1
is19_1     No   Yes
isCAM
No      84522  1370
Yes        67     3
is19_2     No   Yes
isCAM
No      84616  1276
Yes        70     0
is19_3     No   Yes
isCAM
No      83049  2843
Yes        65     5
is19_4     No   Yes
isCAM
No      83844  2048
Yes        67     3
is19_5     No   Yes
isCAM
No      83912  1980
Yes        68     2
is19_6     No   Yes
isCAM
No      84394  1498
Yes        70     0
is51_1     No    Yes
isCAM
No      74439  11453
Yes        67      3
is51_2     No   Yes
isCAM
No      75928  9964
Yes        58    12
is51_3     No   Yes
isCAM
No      81155  4737
Yes        67     3
is51_4     No   Yes
isCAM
No      77591  8301
Yes        58    12
is51_5     No   Yes
isCAM
No      81180  4712
Yes        68     2
is51_6     No   Yes
isCAM
No      82872  3020
Yes        59    11
is2AB_1     No   Yes
isCAM
No       79196  6696
Yes         62     8
is2AB_2     No   Yes
isCAM
No       81972  3920
Yes         61     9
is2AB_3     No   Yes
isCAM
No       77545  8347
Yes         57    13
is2AB_4     No   Yes
isCAM
No       80825  5067
Yes         63     7
is2AB_5     No   Yes
isCAM
No       82973  2919
Yes         66     4
is2AB_6     No   Yes
isCAM
No       80430  5462
Yes         67     3
is52_1     No   Yes
isCAM
No      84581  1311
Yes        66     4
is52_2     No   Yes
isCAM
No      84285  1607
Yes        70     0
is52_3     No   Yes
isCAM
No      84538  1354
Yes        66     4
is52_4     No  Yes
isCAM
No      85112  780
Yes        70    0
is52_5     No  Yes
isCAM
No      85263  629
Yes        70    0
is52_6     No  Yes
isCAM
No      85404  488
Yes        69    1
is46_1     No   Yes
isCAM
No      83195  2697
Yes        68     2
is46_2     No   Yes
isCAM
No      84035  1857
Yes        70     0
is46_3     No   Yes
isCAM
No      83820  2072
Yes        66     4
is46_4     No  Yes
isCAM
No      85143  749
Yes        70    0
is46_5     No   Yes
isCAM
No      84073  1819
Yes        68     2
is46_6     No   Yes
isCAM
No      83720  2172
Yes        64     6
is70_1     No   Yes
isCAM
No      81372  4520
Yes        69     1
is70_2     No   Yes
isCAM
No      82952  2940
Yes        65     5
is70_3     No   Yes
isCAM
No      80057  5835
Yes        59    11
is70_4     No   Yes
isCAM
No      83035  2857
Yes        70     0
is70_5     No   Yes
isCAM
No      81864  4028
Yes        61     9
is70_6     No   Yes
isCAM
No      83434  2458
Yes        67     3
is48_1     No   Yes
isCAM
No      84564  1328
Yes        68     2
is48_2     No  Yes
isCAM
No      85358  534
Yes        70    0
is48_3     No   Yes
isCAM
No      83989  1903
Yes        69     1
is48_4     No   Yes
isCAM
No      84463  1429
Yes        68     2
is48_5     No   Yes
isCAM
No      84734  1158
Yes        65     5
is48_6     No  Yes
isCAM
No      85292  600
Yes        69    1
is55_1     No   Yes
isCAM
No      80904  4988
Yes        66     4
is55_2     No   Yes
isCAM
No      80572  5320
Yes        59    11
is55_3     No   Yes
isCAM
No      82092  3800
Yes        70     0
is55_4     No   Yes
isCAM
No      82797  3095
Yes        66     4
is55_5     No   Yes
isCAM
No      77962  7930
Yes        58    12
is55_6     No   Yes
isCAM
No      79163  6729
Yes        65     5
is18_1     No   Yes
isCAM
No      81010  4882
Yes        67     3
is18_2     No   Yes
isCAM
No      79127  6765
Yes        60    10
is18_3     No   Yes
isCAM
No      83935  1957
Yes        68     2
is18_4     No   Yes
isCAM
No      81271  4621
Yes        62     8
is18_5     No   Yes
isCAM
No      80934  4958
Yes        65     5
is18_6     No  Yes
isCAM
No      84977  915
Yes        70    0
is61_1     No   Yes
isCAM
No      84286  1606
Yes        68     2
is61_2     No   Yes
isCAM
No      76406  9486
Yes        49    21
is61_3     No   Yes
isCAM
No      83009  2883
Yes        69     1
is61_4     No   Yes
isCAM
No      83036  2856
Yes        69     1
is61_5     No   Yes
isCAM
No      80643  5249
Yes        58    12
is61_6     No   Yes
isCAM
No      81641  4251
Yes        67     3
is53_1     No  Yes
isCAM
No      85573  319
Yes        70    0
is53_2     No  Yes
isCAM
No      85237  655
Yes        69    1
is53_3     No  Yes
isCAM
No      85011  881
Yes        69    1
is53_4     No   Yes
isCAM
No      84821  1071
Yes        70     0
is53_5     No  Yes
isCAM
No      85464  428
Yes        70    0
is53_6     No  Yes
isCAM
No      85115  777
Yes        70    0
is56_1     No   Yes
isCAM
No      83850  2042
Yes        68     2

is56_2     No   Yes
isCAM
No      82292  3600
Yes        68     2
is56_3     No   Yes
isCAM
No      82705  3187
Yes        59    11
is56_4     No   Yes
isCAM
No      83360  2532
Yes        67     3
is56_5     No  Yes
isCAM
No      84979  913
Yes        68    2
is56_6     No  Yes
isCAM
No      85184  708
Yes        70    0
is1AB_1     No   Yes
isCAM
No       84484  1408
Yes         68     2
is1AB_2     No   Yes
isCAM
No       81059  4833
Yes         57    13
is1AB_3     No   Yes
isCAM
No       81696  4196
Yes         63     7
is1AB_4     No   Yes
isCAM
No       83195  2697
Yes         68     2
is1AB_5     No   Yes
isCAM
No       82062  3830
Yes         66     4
is1AB_6     No   Yes
isCAM
No       83624  2268
Yes         65     5
is37_1     No   Yes
isCAM
No      80704  5188
Yes        70     0
is37_2     No   Yes
isCAM
No      79351  6541
Yes        63     7
is37_3     No   Yes
isCAM
No      77393  8499
Yes        52    18
is37_4     No    Yes
isCAM
No      75749  10143
Yes        55     15
is37_5     No   Yes
isCAM
No      76689  9203
Yes        66     4
is37_6     No   Yes
isCAM
No      78932  6960
Yes        65     5
isG_1_Ya     No  Yes
isCAM
No        42878  532
Yes          37    3
isG_1_Yf     No  Yes
isCAM
No        42040  442
Yes          28    2
isG_2_Ya     No  Yes
isCAM
No        42922  488
Yes          37    3
isG_2_Yf     No  Yes
isCAM
No        42060  422
Yes          29    1
isG_3_Ya     No  Yes
isCAM
No        43135  275
Yes          39    1
isG_3_Yf     No  Yes
isCAM
No        42216  266
Yes          30    0
isG_4_Ya     No  Yes
isCAM
No        43091  319
Yes          40    0
isG_4_Yf     No  Yes
isCAM
No        42179  303
Yes          30    0
isG_5_Ya     No  Yes
isCAM
No        43335   75
Yes          40    0
isG_5_Yf     No  Yes
isCAM
No        42404   78
Yes          30    0
isG_6_Ya     No  Yes
isCAM
No        43124  286
Yes          39    1
isG_6_Yf     No  Yes
isCAM
No        42197  285
Yes          29    1
isEudy_1_Ya     No  Yes
isCAM
No           42444  966
Yes             40    0
isEudy_1_Yf     No  Yes
isCAM
No           41652  830
Yes             30    0
isEudy_2_Ya     No  Yes
isCAM
No           42572  838
Yes             39    1
isEudy_2_Yf     No  Yes
isCAM
No           41666  816
Yes             30    0
isEudy_3_Ya     No  Yes
isCAM
No           42768  642
Yes             39    1
isEudy_3_Yf     No  Yes
isCAM
No           41896  586
Yes             30    0
isEudy_4_Ya     No   Yes
isCAM
No           42181  1229
Yes             37     3
isEudy_4_Yf     No   Yes
isCAM
No           41320  1162
Yes             29     1
isEudy_5_Ya     No  Yes
isCAM
No           42935  475
Yes             39    1
isEudy_5_Yf     No  Yes
isCAM
No           41982  500
Yes             30    0
isEudy_6_Ya     No  Yes
isCAM
No           42983  427
Yes             40    0
isEudy_6_Yf     No  Yes
isCAM
No           42089  393
Yes             30    0
is36_1_Ya     No   Yes
isCAM
No         39526  3884
Yes           31     9
is36_1_Yf     No   Yes
isCAM
No         38827  3655
Yes           25     5
is36_2_Ya     No   Yes
isCAM
No         40630  2780
Yes           37     3
is36_2_Yf     No   Yes
isCAM
No         39906  2576
Yes           28     2
is36_3_Ya     No   Yes
isCAM
No         42143  1267
Yes           40     0
is36_3_Yf     No   Yes
isCAM
No         41231  1251
Yes           30     0
is36_4_Ya     No   Yes
isCAM
No         41290  2120
Yes           36     4
is36_4_Yf     No   Yes
isCAM
No         40483  1999
Yes           29     1
is36_5_Ya     No   Yes
isCAM
No         42165  1245
Yes           40     0
is36_5_Yf     No   Yes
isCAM
No         41240  1242
Yes           29     1
is36_6_Ya     No   Yes
isCAM
No         41346  2064
Yes           35     5
is36_6_Yf     No   Yes
isCAM
No         40417  2065
Yes           29     1
is43_1_Ya     No   Yes
isCAM
No         41731  1679
Yes           37     3
is43_1_Yf     No   Yes
isCAM
No         40850  1632
Yes           30     0
is43_2_Ya     No   Yes
isCAM
No         39386  4024
Yes           38     2
is43_2_Yf     No   Yes
isCAM
No         38567  3915
Yes           29     1
is43_3_Ya     No   Yes
isCAM
No         37809  5601
Yes           36     4
is43_3_Yf     No   Yes
isCAM
No         37019  5463
Yes           28     2
is43_4_Ya     No   Yes
isCAM
No         40455  2955
Yes           33     7
is43_4_Yf     No   Yes
isCAM
No         39716  2766
Yes           27     3
is43_5_Ya     No   Yes
isCAM
No         40268  3142
Yes           36     4
is43_5_Yf     No   Yes
isCAM
No         39339  3143
Yes           25     5
is43_6_Ya     No   Yes
isCAM
No         41394  2016
Yes           35     5
is43_6_Yf     No   Yes
isCAM
No         40530  1952
Yes           28     2
is13_1_Ya     No  Yes
isCAM
No         42948  462
Yes           39    1
is13_1_Yf     No  Yes
isCAM
No         42043  439
Yes           30    0
is13_2_Ya     No  Yes
isCAM
No         43021  389
Yes           37    3
is13_2_Yf     No  Yes
isCAM
No         42079  403
Yes           28    2
is13_3_Ya     No  Yes
isCAM
No         43069  341
Yes           40    0
is13_3_Yf     No  Yes
isCAM
No         42147  335
Yes           30    0
is13_4_Ya     No  Yes
isCAM
No         42883  527
Yes           38    2
is13_4_Yf     No  Yes
isCAM
No         41986  496
Yes           29    1
is13_5_Ya     No  Yes
isCAM
No         43300  110
Yes           40    0
is13_5_Yf     No  Yes
isCAM
No         42383   99
Yes           30    0
is13_6_Ya     No  Yes
isCAM
No         43262  148
Yes           40    0
is13_6_Yf     No  Yes
isCAM
No         42350  132
Yes           30    0
is45_1_Ya     No  Yes
isCAM
No         42503  907
Yes           36    4
is45_1_Yf     No  Yes
isCAM
No         41605  877
Yes           28    2
is45_2_Ya     No   Yes
isCAM
No         41370  2040
Yes           34     6
is45_2_Yf     No   Yes
isCAM
No         40645  1837
Yes           29     1
is45_3_Ya     No  Yes
isCAM
No         42617  793
Yes           40    0
is45_3_Yf     No  Yes
isCAM
No         41733  749
Yes           30    0
is45_4_Ya     No   Yes
isCAM
No         41674  1736
Yes           37     3
is45_4_Yf     No   Yes
isCAM
No         40848  1634
Yes           28     2
is45_5_Ya     No  Yes
isCAM
No         42469  941
Yes           38    2
is45_5_Yf     No  Yes
isCAM
No         41631  851
Yes           29    1
is45_6_Ya     No   Yes
isCAM
No         41506  1904
Yes           40     0
is45_6_Yf     No   Yes
isCAM
No         40667  1815
Yes           29     1
is19_1_Ya     No  Yes
isCAM
No         42653  757
Yes           38    2
is19_1_Yf     No  Yes
isCAM
No         41869  613
Yes           29    1
is19_2_Ya     No  Yes
isCAM
No         42729  681
Yes           40    0
is19_2_Yf     No  Yes
isCAM
No         41887  595
Yes           30    0

is19_3_Ya     No   Yes
isCAM
No         41945  1465
Yes           37     3
is19_3_Yf     No   Yes
isCAM
No         41104  1378
Yes           28     2
is19_4_Ya     No   Yes
isCAM
No         42356  1054
Yes           39     1
is19_4_Yf     No  Yes
isCAM
No         41488  994
Yes           28    2
is19_5_Ya     No   Yes
isCAM
No         42400  1010
Yes           39     1
is19_5_Yf     No  Yes
isCAM
No         41512  970
Yes           29    1
is19_6_Ya     No  Yes
isCAM
No         42627  783
Yes           40    0
is19_6_Yf     No  Yes
isCAM
No         41767  715
Yes           30    0
is51_1_Ya     No   Yes
isCAM
No         37487  5923
Yes           37     3
is51_1_Yf     No   Yes
isCAM
No         36952  5530
Yes           30     0
is51_2_Ya     No   Yes
isCAM
No         38368  5042
Yes           33     7
is51_2_Yf     No   Yes
isCAM
No         37560  4922
Yes           25     5
is51_3_Ya     No   Yes
isCAM
No         41047  2363
Yes           38     2
is51_3_Yf     No   Yes
isCAM
No         40108  2374
Yes           29     1
is51_4_Ya     No   Yes
isCAM
No         39131  4279
Yes           34     6
is51_4_Yf     No   Yes
isCAM
No         38460  4022
Yes           24     6
is51_5_Ya     No   Yes
isCAM
No         40910  2500
Yes           38     2
is51_5_Yf     No   Yes
isCAM
No         40270  2212
Yes           30     0
is51_6_Ya     No   Yes
isCAM
No         41877  1533
Yes           35     5
is51_6_Yf     No   Yes
isCAM
No         40995  1487
Yes           24     6
is2AB_1_Ya     No   Yes
isCAM
No          39999  3411
Yes            34     6
is2AB_1_Yf     No   Yes
isCAM
No          39197  3285
Yes            28     2
is2AB_2_Ya     No   Yes
isCAM
No          41407  2003
Yes            37     3
is2AB_2_Yf     No   Yes
isCAM
No          40565  1917
Yes            24     6
is2AB_3_Ya     No   Yes
isCAM
No          39036  4374
Yes            31     9
is2AB_3_Yf     No   Yes
isCAM
No          38509  3973
Yes            26     4
is2AB_4_Ya     No   Yes
isCAM
No          40806  2604
Yes            36     4
is2AB_4_Yf     No   Yes
isCAM
No          40019  2463
Yes            27     3
is2AB_5_Ya     No   Yes
isCAM
No          41906  1504
Yes            38     2
is2AB_5_Yf     No   Yes
isCAM
No          41067  1415
Yes            28     2
is2AB_6_Ya     No   Yes
isCAM
No          40635  2775
Yes            38     2
is2AB_6_Yf     No   Yes
isCAM
No          39795  2687
Yes            29     1
is52_1_Ya     No  Yes
isCAM
No         42717  693
Yes           36    4
is52_1_Yf     No  Yes
isCAM
No         41864  618
Yes           30    0
is52_2_Ya     No  Yes
isCAM
No         42611  799
Yes           40    0
is52_2_Yf     No  Yes
isCAM
No         41674  808
Yes           30    0
is52_3_Ya     No  Yes
isCAM
No         42732  678
Yes           37    3
is52_3_Yf     No  Yes
isCAM
No         41806  676
Yes           29    1
is52_4_Ya     No  Yes
isCAM
No         43003  407
Yes           40    0
is52_4_Yf     No  Yes
isCAM
No         42109  373
Yes           30    0
is52_5_Ya     No  Yes
isCAM
No         43080  330
Yes           40    0
is52_5_Yf     No  Yes
isCAM
No         42183  299
Yes           30    0
is52_6_Ya     No  Yes
isCAM
No         43162  248
Yes           40    0
is52_6_Yf     No  Yes
isCAM
No         42242  240
Yes           29    1
is46_1_Ya     No   Yes
isCAM
No         42047  1363
Yes           39     1
is46_1_Yf     No   Yes
isCAM
No         41148  1334
Yes           29     1
is46_2_Ya     No  Yes
isCAM
No         42470  940
Yes           40    0
is46_2_Yf     No  Yes
isCAM
No         41565  917
Yes           30    0
is46_3_Ya     No   Yes
isCAM
No         42357  1053
Yes           38     2
is46_3_Yf     No   Yes
isCAM
No         41463  1019
Yes           28     2
is46_4_Ya     No  Yes
isCAM
No         43022  388
Yes           40    0
is46_4_Yf     No  Yes
isCAM
No         42121  361
Yes           30    0
is46_5_Ya     No  Yes
isCAM
No         42434  976
Yes           38    2
is46_5_Yf     No  Yes
isCAM
No         41639  843
Yes           30    0
is46_6_Ya     No   Yes
isCAM
No         42280  1130
Yes           35     5
is46_6_Yf     No   Yes
isCAM
No         41440  1042
Yes           29     1
is70_1_Ya     No   Yes
isCAM
No         41108  2302
Yes           39     1
is70_1_Yf     No   Yes
isCAM
No         40264  2218
Yes           30     0
is70_2_Ya     No   Yes
isCAM
No         41936  1474
Yes           37     3
is70_2_Yf     No   Yes
isCAM
No         41016  1466
Yes           28     2
is70_3_Ya     No   Yes
isCAM
No         40510  2900
Yes           32     8
is70_3_Yf     No   Yes
isCAM
No         39547  2935
Yes           27     3
is70_4_Ya     No   Yes
isCAM
No         41972  1438
Yes           40     0
is70_4_Yf     No   Yes
isCAM
No         41063  1419
Yes           30     0
is70_5_Ya     No   Yes
isCAM
No         41333  2077
Yes           35     5
is70_5_Yf     No   Yes
isCAM
No         40531  1951
Yes           26     4
is70_6_Ya     No   Yes
isCAM
No         42171  1239
Yes           38     2
is70_6_Yf     No   Yes
isCAM
No         41263  1219
Yes           29     1
is48_1_Ya     No  Yes
isCAM
No         42752  658
Yes           39    1
is48_1_Yf     No  Yes
isCAM
No         41812  670
Yes           29    1
is48_2_Ya     No  Yes
isCAM
No         43115  295
Yes           40    0
is48_2_Yf     No  Yes
isCAM
No         42243  239
Yes           30    0
is48_3_Ya     No  Yes
isCAM
No         42467  943
Yes           39    1
is48_3_Yf     No  Yes
isCAM
No         41522  960
Yes           30    0
is48_4_Ya     No  Yes
isCAM
No         42669  741
Yes           38    2
is48_4_Yf     No  Yes
isCAM
No         41794  688
Yes           30    0
is48_5_Ya     No  Yes
isCAM
No         42831  579
Yes           36    4
is48_5_Yf     No  Yes
isCAM
No         41903  579
Yes           29    1
is48_6_Ya     No  Yes
isCAM
No         43119  291
Yes           40    0
is48_6_Yf     No  Yes
isCAM
No         42173  309
Yes           29    1
is55_1_Ya     No   Yes
isCAM
No         40758  2652
Yes           38     2
is55_1_Yf     No   Yes
isCAM
No         40146  2336
Yes           28     2
is55_2_Ya     No   Yes
isCAM
No         40692  2718
Yes           33     7
is55_2_Yf     No   Yes
isCAM
No         39880  2602
Yes           26     4
is55_3_Ya     No   Yes
isCAM
No         41423  1987
Yes           40     0
is55_3_Yf     No   Yes
isCAM
No         40669  1813
Yes           30     0
is55_4_Ya     No   Yes
isCAM
No         41779  1631
Yes           37     3
is55_4_Yf     No   Yes
isCAM
No         41018  1464
Yes           29     1
is55_5_Ya     No   Yes
isCAM
No         39303  4107
Yes           30    10
is55_5_Yf     No   Yes
isCAM
No         38659  3823
Yes           28     2
is55_6_Ya     No   Yes
isCAM
No         39945  3465
Yes           37     3

is55_6_Yf     No   Yes
isCAM
No         39218  3264
Yes           28     2
is18_1_Ya     No   Yes
isCAM
No         40866  2544
Yes           38     2
is18_1_Yf     No   Yes
isCAM
No         40144  2338
Yes           29     1
is18_2_Ya     No   Yes
isCAM
No         39936  3474
Yes           34     6
is18_2_Yf     No   Yes
isCAM
No         39191  3291
Yes           26     4
is18_3_Ya     No   Yes
isCAM
No         42399  1011
Yes           39     1
is18_3_Yf     No  Yes
isCAM
No         41536  946
Yes           29    1
is18_4_Ya     No   Yes
isCAM
No         41098  2312
Yes           35     5
is18_4_Yf     No   Yes
isCAM
No         40173  2309
Yes           27     3
is18_5_Ya     No   Yes
isCAM
No         40873  2537
Yes           37     3
is18_5_Yf     No   Yes
isCAM
No         40061  2421
Yes           28     2
is18_6_Ya     No  Yes
isCAM
No         42948  462
Yes           40    0
is18_6_Yf     No  Yes
isCAM
No         42029  453
Yes           30    0
is61_1_Ya     No  Yes
isCAM
No         42579  831
Yes           38    2
is61_1_Yf     No  Yes
isCAM
No         41707  775
Yes           30    0
is61_2_Ya     No   Yes
isCAM
No         38672  4738
Yes           27    13
is61_2_Yf     No   Yes
isCAM
No         37734  4748
Yes           22     8
is61_3_Ya     No   Yes
isCAM
No         41907  1503
Yes           39     1
is61_3_Yf     No   Yes
isCAM
No         41102  1380
Yes           30     0
is61_4_Ya     No   Yes
isCAM
No         41985  1425
Yes           39     1
is61_4_Yf     No   Yes
isCAM
No         41051  1431
Yes           30     0
is61_5_Ya     No   Yes
isCAM
No         40700  2710
Yes           31     9
is61_5_Yf     No   Yes
isCAM
No         39943  2539
Yes           27     3
is61_6_Ya     No   Yes
isCAM
No         41220  2190
Yes           38     2
is61_6_Yf     No   Yes
isCAM
No         40421  2061
Yes           29     1
is53_1_Ya     No  Yes
isCAM
No         43249  161
Yes           40    0
is53_1_Yf     No  Yes
isCAM
No         42324  158
Yes           30    0
is53_2_Ya     No  Yes
isCAM
No         43077  333
Yes           39    1
is53_2_Yf     No  Yes
isCAM
No         42160  322
Yes           30    0
is53_3_Ya     No  Yes
isCAM
No         42972  438
Yes           39    1
is53_3_Yf     No  Yes
isCAM
No         42039  443
Yes           30    0
is53_4_Ya     No  Yes
isCAM
No         42887  523
Yes           40    0
is53_4_Yf     No  Yes
isCAM
No         41934  548
Yes           30    0
is53_5_Ya     No  Yes
isCAM
No         43187  223
Yes           40    0
is53_5_Yf     No  Yes
isCAM
No         42277  205
Yes           30    0
is53_6_Ya     No  Yes
isCAM
No         42991  419
Yes           40    0
is53_6_Yf     No  Yes
isCAM
No         42124  358
Yes           30    0
is56_1_Ya     No   Yes
isCAM
No         42320  1090
Yes           39     1
is56_1_Yf     No  Yes
isCAM
No         41530  952
Yes           29    1
is56_2_Ya     No   Yes
isCAM
No         41522  1888
Yes           38     2
is56_2_Yf     No   Yes
isCAM
No         40770  1712
Yes           30     0
is56_3_Ya     No   Yes
isCAM
No         41756  1654
Yes           35     5
is56_3_Yf     No   Yes
isCAM
No         40949  1533
Yes           24     6
is56_4_Ya     No   Yes
isCAM
No         42108  1302
Yes           38     2
is56_4_Yf     No   Yes
isCAM
No         41252  1230
Yes           29     1
is56_5_Ya     No  Yes
isCAM
No         42952  458
Yes           39    1
is56_5_Yf     No  Yes
isCAM
No         42027  455
Yes           29    1
is56_6_Ya     No  Yes
isCAM
No         43049  361
Yes           40    0
is56_6_Yf     No  Yes
isCAM
No         42135  347
Yes           30    0
is1AB_1_Ya     No  Yes
isCAM
No          42707  703
Yes            39    1
is1AB_1_Yf     No  Yes
isCAM
No          41777  705
Yes            29    1
is1AB_2_Ya     No   Yes
isCAM
No          40900  2510
Yes            31     9
is1AB_2_Yf     No   Yes
isCAM
No          40159  2323
Yes            26     4
is1AB_3_Ya     No   Yes
isCAM
No          41211  2199
Yes            36     4
is1AB_3_Yf     No   Yes
isCAM
No          40485  1997
Yes            27     3
is1AB_4_Ya     No   Yes
isCAM
No          41971  1439
Yes            39     1
is1AB_4_Yf     No   Yes
isCAM
No          41224  1258
Yes            29     1
is1AB_5_Ya     No   Yes
isCAM
No          41460  1950
Yes            38     2
is1AB_5_Yf     No   Yes
isCAM
No          40602  1880
Yes            28     2
is1AB_6_Ya     No   Yes
isCAM
No          42266  1144
Yes            38     2
is1AB_6_Yf     No   Yes
isCAM
No          41358  1124
Yes            27     3
is37_1_Ya     No   Yes
isCAM
No         40788  2622
Yes           40     0
is37_1_Yf     No   Yes
isCAM
No         39916  2566
Yes           30     0
is37_2_Ya     No   Yes
isCAM
No         40077  3333
Yes           37     3
is37_2_Yf     No   Yes
isCAM
No         39274  3208
Yes           26     4
is37_3_Ya     No   Yes
isCAM
No         39112  4298
Yes           27    13
is37_3_Yf     No   Yes
isCAM
No         38281  4201
Yes           25     5
is37_4_Ya     No   Yes
isCAM
No         38228  5182
Yes           30    10
is37_4_Yf     No   Yes
isCAM
No         37521  4961
Yes           25     5
is37_5_Ya     No   Yes
isCAM
No         38760  4650
Yes           37     3
is37_5_Yf     No   Yes
isCAM
No         37929  4553
Yes           29     1
is37_6_Ya     No   Yes
isCAM
No         39894  3516
Yes           38     2
is37_6_Yf     No   Yes
isCAM
No         39038  3444
Yes           27     3

In [97]:
gtcres[gtcres["P-adj"]<0.05]

        Group   P-value  Odds Ratio     P-adj
0         G_1  0.001246    6.706523  0.032032
25       13_2  0.000498    8.265346  0.019235
47       51_6  0.000033    5.116130  0.005890
91       61_2  0.000014    3.451974  0.005005
94       61_5  0.001044    3.178655  0.028898
104      56_3  0.000053    4.838273  0.006371
109     1AB_2  0.000131    3.825189  0.007874
116      37_3  0.000121    3.152122  0.007874
215   51_6_Yf  0.000534    6.892233  0.019235
219  2AB_2_Yf  0.001979    5.290167  0.044988
272   48_5_Ya  0.001999    8.219344  0.044988
302   61_2_Ya  0.000217    3.929897  0.011171
308   61_5_Ya  0.000674    4.360195  0.020233
329   56_3_Yf  0.000627    6.677919  0.020233
338  1AB_2_Ya  0.000387    4.730754  0.017411
352   37_3_Ya  0.000081    4.381504  0.007271

In [147]:
# now run ZTpeaks
ztpres = test_enrichment(ztplist,"CAM")

is1.0     No    Yes
isCAM
No     58799  27093
Yes       32     38
is9.0     No    Yes
isCAM
No     51800  34092
Yes       28     42
is5.0     No    Yes
isCAM
No     55255  30637
Yes       29     41
is21.0     No    Yes
isCAM
No      57251  28641
Yes        44     26
is13.0     No    Yes
isCAM
No      62734  23158
Yes        51     19
is17.0     No    Yes
isCAM
No      57804  28088
Yes        45     25
is1.0_Ya     No    Yes
isCAM
No        29887  13523
Yes          18     22
is1.0_Yf     No    Yes
isCAM
No        28912  13570
Yes          14     16
is9.0_Ya     No    Yes
isCAM
No        26347  17063
Yes          15     25
is9.0_Yf     No    Yes
isCAM
No        25453  17029
Yes          13     17
is5.0_Ya     No    Yes
isCAM
No        28080  15330
Yes          14     26
is5.0_Yf     No    Yes
isCAM
No        27175  15307
Yes          15     15
is21.0_Ya     No    Yes
isCAM
No         29122  14288
Yes           26     14
is21.0_Yf     No    Yes
isCAM
No         28129  14353
Yes           18     12
is13.0_Ya     No    Yes
isCAM
No         31565  11845
Yes           28     12
is13.0_Yf     No    Yes
isCAM
No         31169  11313
Yes           23      7
is17.0_Ya     No    Yes
isCAM
No         29121  14289
Yes           22     18
is17.0_Yf     No    Yes
isCAM
No         28683  13799
Yes           23      7

In [104]:
ztpres[ztpres["P-adj"]<0.05]

     Group   P-value  Odds Ratio     P-adj
0      1.0  0.000088    2.577190  0.001061
1      9.0  0.000832    2.279127  0.003746
2      5.0  0.000137    2.549830  0.001061
6   1.0_Ya  0.001850    2.701217  0.006660
7   1.0_Yf  0.017399    2.434951  0.044739
8   9.0_Ya  0.003332    2.573502  0.009997
10  5.0_Ya  0.000177    3.401733  0.001061

In [148]:
# append all results dataframes together
allres = pd.concat([sgres,ztpres,gtres,gtcres])

In [149]:
# out of curiosity: do FDR pvals change when the n is much higher?
allres["P-adj_highN"] = fdrcorrection(allres["P-value"])[1]

In [150]:
allres.head()

  Group   P-value  Odds Ratio     P-adj  P-adj_highN
0    Ya  0.000217         inf  0.000613     0.005989
1    Yf  0.250692    2.151432  0.250692     0.636521
2   all  0.000408    5.454572  0.000613     0.009478
0   1.0  0.000088    2.577190  0.001061     0.003894
1   9.0  0.000832    2.279127  0.003746     0.015295

In [151]:
# yes - high n is more conservative (at least in most cases)
# get significant results based on P-adj_highN column
sigres = allres[allres["P-adj_highN"]<0.05]

In [152]:
len(allres[allres["P-adj"]<0.05].index)

49

In [153]:
len(sigres.index)

50

In [154]:
# create a subgenome column in sigres
subg = []
for i in list(sigres["Group"]):
    if "Ya" in i:
        subg.append("Ya")
    elif "Yf" in i:
        subg.append("Yf")
    else:
        subg.append("both")

In [155]:
sigres["subgenome"] = subg
sigres.head()

/tmp/ipykernel_140/1116880248.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sigres["subgenome"] = subg

  Group   P-value  Odds Ratio     P-adj  P-adj_highN subgenome
0    Ya  0.000217         inf  0.000613     0.005989        Ya
2   all  0.000408    5.454572  0.000613     0.009478      both
0   1.0  0.000088    2.577190  0.001061     0.003894      both
1   9.0  0.000832    2.279127  0.003746     0.015295      both
2   5.0  0.000137    2.549830  0.001061     0.004661      both

In [156]:
sigres.groupby("subgenome").count().reset_index()[["subgenome","Group"]]

  subgenome  Group
0        Ya     22
1        Yf      4
2      both     24

In [157]:
sigres[sigres["subgenome"]=="Yf"]

        Group   P-value  Odds Ratio     P-adj  P-adj_highN subgenome
57     1AB_Yf  0.002853    3.127557  0.017115     0.036999        Yf
215   51_6_Yf  0.000534    6.892233  0.019235     0.011220        Yf
219  2AB_2_Yf  0.001979    5.290167  0.044988     0.028444        Yf
329   56_3_Yf  0.000627    6.677919  0.020233     0.012566        Yf

In [158]:
# create a "group type" column for sigres (for easier filtering)
grptype = []
for i in list(sigres["Group"]):
    if i in sg:
        grptype.append("overall_TSgenes")
    elif i in gtlist:
        grptype.append("genotype_TSgenes")
    elif i in gtclist:
        grptype.append("individual_cluster")
    elif i in ztplist:
        grptype.append("ZTpeak_clustergroup")
sigres["group_type"] = grptype
sigres.head()

/tmp/ipykernel_140/3525569891.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sigres["group_type"] = grptype

,Group,P-value,Odds Ratio,P-adj,P-adj_highN,subgenome,group_type
0,Ya,0.000217,inf,0.000613,0.005989,Ya,overall_TSgenes
2,all,0.000408,5.454572,0.000613,0.009478,both,overall_TSgenes
0,1.0,0.000088,2.577190,0.001061,0.003894,both,ZTpeak_clustergroup
1,9.0,0.000832,2.279127,0.003746,0.015295,both,ZTpeak_clustergroup
2,5.0,0.000137,2.549830,0.001061,0.004661,both,ZTpeak_clustergroup

In [159]:
sigres[sigres["group_type"]=="overall_TSgenes"]

,Group,P-value,Odds Ratio,P-adj,P-adj_highN,subgenome,group_type
0,Ya,0.000217,inf,0.000613,0.005989,Ya,overall_TSgenes
2,all,0.000408,5.454572,0.000613,0.009478,both,overall_TSgenes

In [160]:
sigres[sigres["group_type"]=="ZTpeak_clustergroup"]

,Group,P-value,Odds Ratio,P-adj,P-adj_highN,subgenome,group_type
0,1.0,0.000088,2.577190,0.001061,0.003894,both,ZTpeak_clustergroup
1,9.0,0.000832,2.279127,0.003746,0.015295,both,ZTpeak_clustergroup
2,5.0,0.000137,2.549830,0.001061,0.004661,both,ZTpeak_clustergroup
6,1.0_Ya,0.001850,2.701217,0.006660,0.028131,Ya,ZTpeak_clustergroup
8,9.0_Ya,0.003332,2.573502,0.009997,0.039639,Ya,ZTpeak_clustergroup
10,5.0_Ya,0.000177,3.401733,0.001061,0.005571,Ya,ZTpeak_clustergroup

In [161]:
sigres[sigres["group_type"]=="genotype_TSgenes"]

,Group,P-value,Odds Ratio,P-adj,P-adj_highN,subgenome,group_type
0,G,5.113546e-05,4.505583,0.000614,0.002927,both,genotype_TSgenes
4,13,4.237065e-03,3.117749,0.018159,0.042415,both,genotype_TSgenes
8,2AB,3.204128e-05,2.792457,0.000481,0.002405,both,genotype_TSgenes
15,61,5.780650e-06,3.016014,0.000116,0.000850,both,genotype_TSgenes
17,56,3.864996e-03,2.246495,0.017838,0.039639,both,genotype_TSgenes
18,1AB,4.811459e-06,3.091385,0.000116,0.000850,both,genotype_TSgenes
20,G_Ya,3.858391e-04,5.244937,0.003858,0.009478,Ya,genotype_TSgenes
24,36_Ya,5.285763e-03,2.486015,0.021143,0.048450,Ya,genotype_TSgenes
36,2AB_Ya,8.928607e-04,2.978714,0.007034,0.015750,Ya,genotype_TSgenes
42,70_Ya,3.826409e-03,2.531434,0.017838,0.039639,Ya,genotype_TSgenes
46,55_Ya,2.834022e-03,2.702295,0.017115,0.036999,Ya,genotype_TSgenes
50,61_Ya,4.167731e-07,5.227315,0.000025,0.000184,Ya,genotype_TSgenes
56,1AB_Ya,9.378808e-04,3.044531,0.007034,0.015908,Ya,genotype_TSgenes
57,1AB_Yf,2.852568e-03,3.127557,0.017115,0.036999,Yf,genotype_TSgenes
58,37_Ya,3.731162e-03,2.891022,0.017838,0.039639,Ya,genotype_TSgenes

In [162]:
sigres[sigres["group_type"]=="individual_cluster"]

,Group,P-value,Odds Ratio,P-adj,P-adj_highN,subgenome,group_type
0,G_1,0.001246,6.706523,0.032032,0.019620,both,individual_cluster
12,36_1,0.004385,2.598256,0.065095,0.042415,both,individual_cluster
25,13_2,0.000498,8.265346,0.019235,0.010980,both,individual_cluster
30,45_1,0.003410,4.419913,0.062112,0.039639,both,individual_cluster
47,51_6,0.000033,5.116130,0.005890,0.002405,both,individual_cluster
49,2AB_2,0.004520,3.085263,0.065095,0.042415,both,individual_cluster
70,70_5,0.005383,2.998584,0.074539,0.048450,both,individual_cluster
76,48_5,0.002632,5.628670,0.055732,0.036270,both,individual_cluster
79,55_2,0.003744,2.823665,0.062112,0.039639,both,individual_cluster
91,61_2,0.000014,3.451974,0.005005,0.001533,both,individual_cluster
94,61_5,0.001044,3.178655,0.028898,0.017044,both,individual_cluster
104,56_3,0.000053,4.838273,0.006371,0.002927,both,individual_cluster
109,1AB_2,0.000131,3.825189,0.007874,0.004661,both,individual_cluster
116,37_3,0.000121,3.152122,0.007874,0.004661,both,individual_cluster
170,13_2_Ya,0.005623,8.967067,0.074968,0.049592,Ya,individual_cluster
215,51_6_Yf,0.000534,6.892233,0.019235,0.011220,Yf,individual_cluster
219,2AB_2_Yf,0.001979,5.290167,0.044988,0.028444,Yf,individual_cluster
228,52_1_Ya,0.003796,6.848966,0.062112,0.039639,Ya,individual_cluster
250,46_6_Ya,0.003717,5.345133,0.062112,0.039639,Ya,individual_cluster
256,70_3_Ya,0.004450,3.492241,0.065095,0.042415,Ya,individual_cluster
272,48_5_Ya,0.001999,8.219344,0.044988,0.028444,Ya,individual_cluster
284,55_5_Ya,0.003423,3.189920,0.062112,0.039639,Ya,individual_cluster
302,61_2_Ya,0.000217,3.929897,0.011171,0.005989,Ya,individual_cluster
308,61_5_Ya,0.000674,4.360195,0.020233,0.012931,Ya,individual_cluster
329,56_3_Yf,0.000627,6.677919,0.020233,0.012566,Yf,individual_cluster
338,1AB_2_Ya,0.000387,4.730754,0.017411,0.009478,Ya,individual_cluster
352,37_3_Ya,0.000081,4.381504,0.007271,0.003894,Ya,individual_cluster

In [163]:
# save both allres and sigres
allres.to_csv("./camenrich_tsgenes_allp.txt",sep="\t",header=True,index=False)
sigres.to_csv("./camenrich_tsgenes_sigp.txt",sep="\t",header=True,index=False)

In [165]:
cam["Pathway"].unique()

array(['CAM-dark', 'CAM-light'], dtype=object)

In [166]:
# repeat for CAM-dark and CAM-light
darkres = test_enrichment(allgroups,"CAM-dark")

isYa          No    Yes
isCAM-dark
No          8664  34760
Yes            0     26
isYf          No    Yes
isCAM-dark
No          8197  34294
Yes            2     19
isall          No    Yes
isCAM-dark
No          16861  69054
Yes             2     45
isG            No   Yes
isCAM-dark
No          82140  3775
Yes            39     8
isEudy         No   Yes
isCAM-dark
No          77046  8869
Yes            45     2
is36           No    Yes
isCAM-dark
No          59755  26160
Yes            28     19
is43           No    Yes
isCAM-dark
No          47614  38301
Yes            22     25
is13           No   Yes
isCAM-dark
No          82030  3885
Yes            42     5
is45           No    Yes
isCAM-dark
No          69821  16094
Yes            35     12
is19           No    Yes
isCAM-dark
No          74898  11017
Yes            36     11
is51           No    Yes
isCAM-dark
No          43713  42202
Yes            19     28
is2AB          No    Yes
isCAM-dark
No          53490  32425
Yes            17     30
is52           No   Yes
isCAM-dark
No          79741  6174
Yes            43     4
is46           No    Yes
isCAM-dark
No          74543  11372
Yes            39      8
is70           No    Yes
isCAM-dark
No          63265  22650
Yes            30     17
is48           No   Yes
isCAM-dark
No          78957  6958
Yes            42     5
is55           No    Yes
isCAM-dark
No          54037  31878
Yes            27     20
is18           No    Yes
isCAM-dark
No          61803  24112
Yes            33     14
is61           No    Yes
isCAM-dark
No          59568  26347
Yes            23     24
is53           No   Yes
isCAM-dark
No          81784  4131
Yes            45     2
is56           No    Yes
isCAM-dark
No          72924  12991
Yes            36     11
is1AB          No    Yes
isCAM-dark
No          66670  19245
Yes            27     20
is37           No    Yes
isCAM-dark
No          39364  46551
Yes            15     32
isG_Ya         No   Yes
isCAM-dark
No          41446  1978
Yes            21     5
isG_Yf         No   Yes
isCAM-dark
No          40694  1797
Yes            18     3
isEudy_Ya      No   Yes
isCAM-dark
No          38843  4581
Yes            24     2
isEudy_Yf      No   Yes
isCAM-dark
No          38203  4288
Yes            21     0
is36_Ya        No    Yes
isCAM-dark
No          30055  13369
Yes            14     12
is36_Yf        No    Yes
isCAM-dark
No          29700  12791
Yes            14      7
is43_Ya        No    Yes
isCAM-dark
No          23997  19427
Yes            11     15
is43_Yf        No    Yes
isCAM-dark
No          23617  18874
Yes            11     10
is13_Ya        No   Yes
isCAM-dark
No          41444  1980
Yes            23     3
is13_Yf        No   Yes
isCAM-dark
No          40586  1905
Yes            19     2
is45_Ya        No   Yes
isCAM-dark
No          35096  8328
Yes            18     8
is45_Yf        No   Yes
isCAM-dark
No          34725  7766
Yes            17     4
is19_Ya        No   Yes
isCAM-dark
No          37673  5751
Yes            20     6
is19_Yf        No   Yes
isCAM-dark
No          37225  5266
Yes            16     5
is51_Ya        No    Yes
isCAM-dark
No          21774  21650
Yes            11     15
is51_Yf        No    Yes
isCAM-dark
No          21939  20552
Yes             8     13
is2AB_Ya       No    Yes
isCAM-dark
No          26744  16680
Yes             9     17
is2AB_Yf       No    Yes
isCAM-dark
No          26746  15745
Yes             8     13
is52_Ya        No   Yes
isCAM-dark
No          40265  3159
Yes            23     3
is52_Yf        No   Yes
isCAM-dark
No          39476  3015
Yes            20     1
is46_Ya        No   Yes
isCAM-dark
No          37569  5855
Yes            21     5
is46_Yf        No   Yes
isCAM-dark
No          36974  5517
Yes            18     3
is70_Ya        No    Yes
isCAM-dark
No          31986  11438
Yes            15     11
is70_Yf        No    Yes
isCAM-dark
No          31279  11212
Yes            15      6
is48_Ya        No   Yes
isCAM-dark
No          39912  3512
Yes            23     3
is48_Yf        No   Yes
isCAM-dark
No          39045  3446
Yes            19     2
is55_Ya        No    Yes
isCAM-dark
No          26853  16571
Yes            12     14
is55_Yf        No    Yes
isCAM-dark
No          27184  15307
Yes            15      6
is18_Ya        No    Yes
isCAM-dark
No          31076  12348
Yes            17      9
is18_Yf        No    Yes
isCAM-dark
No          30727  11764
Yes            16      5
is61_Ya        No    Yes
isCAM-dark
No          30015  13409
Yes            10     16
is61_Yf        No    Yes
isCAM-dark
No          29553  12938
Yes            13      8
is53_Ya        No   Yes
isCAM-dark
No          41327  2097
Yes            24     2
is53_Yf        No   Yes
isCAM-dark
No          40457  2034
Yes            21     0
is56_Ya        No   Yes
isCAM-dark
No          36665  6759
Yes            21     5
is56_Yf        No   Yes
isCAM-dark
No          36259  6232
Yes            15     6
is1AB_Ya       No   Yes
isCAM-dark
No          33469  9955
Yes            17     9
is1AB_Yf       No   Yes
isCAM-dark
No          33201  9290
Yes            10    11
is37_Ya        No    Yes
isCAM-dark
No          19812  23612
Yes             6     20
is37_Yf        No    Yes
isCAM-dark
No          19552  22939
Yes             9     12
isG_1          No  Yes
isCAM-dark
No          84938  977
Yes            45    2
isG_2          No  Yes
isCAM-dark
No          85005  910
Yes            43    4
isG_3          No  Yes
isCAM-dark
No          85373  542
Yes            47    0
isG_4          No  Yes
isCAM-dark
No          85293  622
Yes            47    0
isG_5          No  Yes
isCAM-dark
No          85762  153
Yes            47    0
isG_6          No  Yes
isCAM-dark
No          85344  571
Yes            45    2
isEudy_1       No   Yes
isCAM-dark
No          84119  1796
Yes            47     0
isEudy_2       No   Yes
isCAM-dark
No          84261  1654
Yes            46     1
isEudy_3       No   Yes
isCAM-dark
No          84686  1229
Yes            47     0
isEudy_4       No   Yes
isCAM-dark
No          83520  2395
Yes            47     0
isEudy_5       No  Yes
isCAM-dark
No          84940  975
Yes            46    1
isEudy_6       No  Yes
isCAM-dark
No          85095  820
Yes            47    0
is36_1         No   Yes
isCAM-dark
No          78372  7543
Yes            37    10
is36_2         No   Yes
isCAM-dark
No          80558  5357
Yes            43     4
is36_3         No   Yes
isCAM-dark
No          83397  2518
Yes            47     0
is36_4         No   Yes
isCAM-dark
No          81791  4124
Yes            47     0
is36_5         No   Yes
isCAM-dark
No          83428  2487
Yes            46     1
is36_6         No   Yes
isCAM-dark
No          81784  4131
Yes            43     4
is43_1         No   Yes
isCAM-dark
No          82602  3313
Yes            46     1
is43_2         No   Yes
isCAM-dark
No          77974  7941
Yes            46     1
is43_3         No    Yes
isCAM-dark
No          74850  11065
Yes            42      5
is43_4         No   Yes
isCAM-dark
No          80191  5724
Yes            40     7

is43_5         No   Yes
isCAM-dark
No          79627  6288
Yes            41     6
is43_6         No   Yes
isCAM-dark
No          81945  3970
Yes            42     5
is13_1         No  Yes
isCAM-dark
No          85014  901
Yes            46    1
is13_2         No  Yes
isCAM-dark
No          85122  793
Yes            43    4
is13_3         No  Yes
isCAM-dark
No          85239  676
Yes            47    0
is13_4         No   Yes
isCAM-dark
No          84889  1026
Yes            47     0
is13_5         No  Yes
isCAM-dark
No          85706  209
Yes            47    0
is13_6         No  Yes
isCAM-dark
No          85635  280
Yes            47    0
is45_1         No   Yes
isCAM-dark
No          84126  1789
Yes            46     1
is45_2         No   Yes
isCAM-dark
No          82036  3879
Yes            42     5
is45_3         No   Yes
isCAM-dark
No          84373  1542
Yes            47     0
is45_4         No   Yes
isCAM-dark
No          82543  3372
Yes            44     3
is45_5         No   Yes
isCAM-dark
No          84122  1793
Yes            45     2
is45_6         No   Yes
isCAM-dark
No          82196  3719
Yes            46     1
is19_1         No   Yes
isCAM-dark
No          84545  1370
Yes            44     3
is19_2         No   Yes
isCAM-dark
No          84639  1276
Yes            47     0
is19_3         No   Yes
isCAM-dark
No          83070  2845
Yes            44     3
is19_4         No   Yes
isCAM-dark
No          83867  2048
Yes            44     3
is19_5         No   Yes
isCAM-dark
No          83935  1980
Yes            45     2
is19_6         No   Yes
isCAM-dark
No          84417  1498
Yes            47     0
is51_1         No    Yes
isCAM-dark
No          74461  11454
Yes            45      2
is51_2         No   Yes
isCAM-dark
No          75948  9967
Yes            38     9
is51_3         No   Yes
isCAM-dark
No          81176  4739
Yes            46     1
is51_4         No   Yes
isCAM-dark
No          77609  8306
Yes            40     7
is51_5         No   Yes
isCAM-dark
No          81202  4713
Yes            46     1
is51_6         No   Yes
isCAM-dark
No          82892  3023
Yes            39     8
is2AB_1        No   Yes
isCAM-dark
No          79215  6700
Yes            43     4
is2AB_2        No   Yes
isCAM-dark
No          81993  3922
Yes            40     7
is2AB_3        No   Yes
isCAM-dark
No          77564  8351
Yes            38     9
is2AB_4        No   Yes
isCAM-dark
No          80845  5070
Yes            43     4
is2AB_5        No   Yes
isCAM-dark
No          82995  2920
Yes            44     3
is2AB_6        No   Yes
isCAM-dark
No          80453  5462
Yes            44     3
is52_1         No   Yes
isCAM-dark
No          84602  1313
Yes            45     2
is52_2         No   Yes
isCAM-dark
No          84308  1607
Yes            47     0
is52_3         No   Yes
isCAM-dark
No          84558  1357
Yes            46     1
is52_4         No  Yes
isCAM-dark
No          85135  780
Yes            47    0
is52_5         No  Yes
isCAM-dark
No          85286  629
Yes            47    0
is52_6         No  Yes
isCAM-dark
No          85427  488
Yes            46    1
is46_1         No   Yes
isCAM-dark
No          83218  2697
Yes            45     2
is46_2         No   Yes
isCAM-dark
No          84058  1857
Yes            47     0
is46_3         No   Yes
isCAM-dark
No          83840  2075
Yes            46     1
is46_4         No  Yes
isCAM-dark
No          85166  749
Yes            47    0
is46_5         No   Yes
isCAM-dark
No          84095  1820
Yes            46     1
is46_6         No   Yes
isCAM-dark
No          83741  2174
Yes            43     4
is70_1         No   Yes
isCAM-dark
No          81395  4520
Yes            46     1
is70_2         No   Yes
isCAM-dark
No          82974  2941
Yes            43     4
is70_3         No   Yes
isCAM-dark
No          80075  5840
Yes            41     6
is70_4         No   Yes
isCAM-dark
No          83058  2857
Yes            47     0
is70_5         No   Yes
isCAM-dark
No          81882  4033
Yes            43     4
is70_6         No   Yes
isCAM-dark
No          83456  2459
Yes            45     2
is48_1         No   Yes
isCAM-dark
No          84586  1329
Yes            46     1
is48_2         No  Yes
isCAM-dark
No          85381  534
Yes            47    0
is48_3         No   Yes
isCAM-dark
No          84011  1904
Yes            47     0
is48_4         No   Yes
isCAM-dark
No          84484  1431
Yes            47     0
is48_5         No   Yes
isCAM-dark
No          84755  1160
Yes            44     3
is48_6         No  Yes
isCAM-dark
No          85315  600
Yes            46    1
is55_1         No   Yes
isCAM-dark
No          80926  4989
Yes            44     3
is55_2         No   Yes
isCAM-dark
No          80588  5327
Yes            43     4
is55_3         No   Yes
isCAM-dark
No          82115  3800
Yes            47     0
is55_4         No   Yes
isCAM-dark
No          82820  3095
Yes            43     4
is55_5         No   Yes
isCAM-dark
No          77977  7938
Yes            43     4
is55_6         No   Yes
isCAM-dark
No          79186  6729
Yes            42     5
is18_1         No   Yes
isCAM-dark
No          81031  4884
Yes            46     1
is18_2         No   Yes
isCAM-dark
No          79148  6767
Yes            39     8
is18_3         No   Yes
isCAM-dark
No          83958  1957
Yes            45     2
is18_4         No   Yes
isCAM-dark
No          81289  4626
Yes            44     3
is18_5         No   Yes
isCAM-dark
No          80952  4963
Yes            47     0
is18_6         No  Yes
isCAM-dark
No          85000  915
Yes            47    0
is61_1         No   Yes
isCAM-dark
No          84309  1606
Yes            45     2
is61_2         No   Yes
isCAM-dark
No          76419  9496
Yes            36    11
is61_3         No   Yes
isCAM-dark
No          83031  2884
Yes            47     0
is61_4         No   Yes
isCAM-dark
No          83059  2856
Yes            46     1
is61_5         No   Yes
isCAM-dark
No          80661  5254
Yes            40     7
is61_6         No   Yes
isCAM-dark
No          81664  4251
Yes            44     3
is53_1         No  Yes
isCAM-dark
No          85596  319
Yes            47    0
is53_2         No  Yes
isCAM-dark
No          85260  655
Yes            46    1
is53_3         No  Yes
isCAM-dark
No          85034  881
Yes            46    1
is53_4         No   Yes
isCAM-dark
No          84844  1071
Yes            47     0
is53_5         No  Yes
isCAM-dark
No          85487  428
Yes            47    0
is53_6         No  Yes
isCAM-dark
No          85138  777
Yes            47    0
is56_1         No   Yes
isCAM-dark
No          83872  2043
Yes            46     1
is56_2         No   Yes
isCAM-dark
No          82315  3600
Yes            45     2
is56_3         No   Yes
isCAM-dark
No          82723  3192
Yes            41     6
is56_4         No   Yes
isCAM-dark
No          83380  2535
Yes            47     0
is56_5         No  Yes
isCAM-dark
No          85002  913
Yes            45    2
is56_6         No  Yes
isCAM-dark
No          85207  708
Yes            47    0
is1AB_1        No   Yes
isCAM-dark
No          84507  1408
Yes            45     2

is1AB_2        No   Yes
isCAM-dark
No          81077  4838
Yes            39     8
is1AB_3        No   Yes
isCAM-dark
No          81715  4200
Yes            44     3
is1AB_4        No   Yes
isCAM-dark
No          83217  2698
Yes            46     1
is1AB_5        No   Yes
isCAM-dark
No          82084  3831
Yes            44     3
is1AB_6        No   Yes
isCAM-dark
No          83645  2270
Yes            44     3
is37_1         No   Yes
isCAM-dark
No          80727  5188
Yes            47     0
is37_2         No   Yes
isCAM-dark
No          79371  6544
Yes            43     4
is37_3         No   Yes
isCAM-dark
No          77410  8505
Yes            35    12
is37_4         No    Yes
isCAM-dark
No          75767  10148
Yes            37     10
is37_5         No   Yes
isCAM-dark
No          76712  9203
Yes            43     4
is37_6         No   Yes
isCAM-dark
No          78952  6963
Yes            45     2
isG_1_Ya       No  Yes
isCAM-dark
No          42890  534
Yes            25    1
isG_1_Yf       No  Yes
isCAM-dark
No          42048  443
Yes            20    1
isG_2_Ya       No  Yes
isCAM-dark
No          42936  488
Yes            23    3
isG_2_Yf       No  Yes
isCAM-dark
No          42069  422
Yes            20    1
isG_3_Ya       No  Yes
isCAM-dark
No          43148  276
Yes            26    0
isG_3_Yf       No  Yes
isCAM-dark
No          42225  266
Yes            21    0
isG_4_Ya       No  Yes
isCAM-dark
No          43105  319
Yes            26    0
isG_4_Yf       No  Yes
isCAM-dark
No          42188  303
Yes            21    0
isG_5_Ya       No  Yes
isCAM-dark
No          43349   75
Yes            26    0
isG_5_Yf       No  Yes
isCAM-dark
No          42413   78
Yes            21    0
isG_6_Ya       No  Yes
isCAM-dark
No          43138  286
Yes            25    1
isG_6_Yf       No  Yes
isCAM-dark
No          42206  285
Yes            20    1
isEudy_1_Ya     No  Yes
isCAM-dark
No           42458  966
Yes             26    0
isEudy_1_Yf     No  Yes
isCAM-dark
No           41661  830
Yes             21    0
isEudy_2_Ya     No  Yes
isCAM-dark
No           42586  838
Yes             25    1
isEudy_2_Yf     No  Yes
isCAM-dark
No           41675  816
Yes             21    0
isEudy_3_Ya     No  Yes
isCAM-dark
No           42781  643
Yes             26    0
isEudy_3_Yf     No  Yes
isCAM-dark
No           41905  586
Yes             21    0
isEudy_4_Ya     No   Yes
isCAM-dark
No           42192  1232
Yes             26     0
isEudy_4_Yf     No   Yes
isCAM-dark
No           41328  1163
Yes             21     0
isEudy_5_Ya     No  Yes
isCAM-dark
No           42949  475
Yes             25    1
isEudy_5_Yf     No  Yes
isCAM-dark
No           41991  500
Yes             21    0
isEudy_6_Ya     No  Yes
isCAM-dark
No           42997  427
Yes             26    0
isEudy_6_Yf     No  Yes
isCAM-dark
No           42098  393
Yes             21    0
is36_1_Ya      No   Yes
isCAM-dark
No          39537  3887
Yes            20     6
is36_1_Yf      No   Yes
isCAM-dark
No          38835  3656
Yes            17     4
is36_2_Ya      No   Yes
isCAM-dark
No          40644  2780
Yes            23     3
is36_2_Yf      No   Yes
isCAM-dark
No          39914  2577
Yes            20     1
is36_3_Ya      No   Yes
isCAM-dark
No          42157  1267
Yes            26     0
is36_3_Yf      No   Yes
isCAM-dark
No          41240  1251
Yes            21     0
is36_4_Ya      No   Yes
isCAM-dark
No          41300  2124
Yes            26     0
is36_4_Yf      No   Yes
isCAM-dark
No          40491  2000
Yes            21     0
is36_5_Ya      No   Yes
isCAM-dark
No          42179  1245
Yes            26     0
is36_5_Yf      No   Yes
isCAM-dark
No          41249  1242
Yes            20     1
is36_6_Ya      No   Yes
isCAM-dark
No          41358  2066
Yes            23     3
is36_6_Yf      No   Yes
isCAM-dark
No          40426  2065
Yes            20     1
is43_1_Ya      No   Yes
isCAM-dark
No          41743  1681
Yes            25     1
is43_1_Yf      No   Yes
isCAM-dark
No          40859  1632
Yes            21     0
is43_2_Ya      No   Yes
isCAM-dark
No          39399  4025
Yes            25     1
is43_2_Yf      No   Yes
isCAM-dark
No          38575  3916
Yes            21     0
is43_3_Ya      No   Yes
isCAM-dark
No          37822  5602
Yes            23     3
is43_3_Yf      No   Yes
isCAM-dark
No          37028  5463
Yes            19     2
is43_4_Ya      No   Yes
isCAM-dark
No          40466  2958
Yes            22     4
is43_4_Yf      No   Yes
isCAM-dark
No          39725  2766
Yes            18     3
is43_5_Ya      No   Yes
isCAM-dark
No          40281  3143
Yes            23     3
is43_5_Yf      No   Yes
isCAM-dark
No          39346  3145
Yes            18     3
is43_6_Ya      No   Yes
isCAM-dark
No          41406  2018
Yes            23     3
is43_6_Yf      No   Yes
isCAM-dark
No          40539  1952
Yes            19     2
is13_1_Ya      No  Yes
isCAM-dark
No          42962  462
Yes            25    1
is13_1_Yf      No  Yes
isCAM-dark
No          42052  439
Yes            21    0
is13_2_Ya      No  Yes
isCAM-dark
No          43034  390
Yes            24    2
is13_2_Yf      No  Yes
isCAM-dark
No          42088  403
Yes            19    2
is13_3_Ya      No  Yes
isCAM-dark
No          43083  341
Yes            26    0
is13_3_Yf      No  Yes
isCAM-dark
No          42156  335
Yes            21    0
is13_4_Ya      No  Yes
isCAM-dark
No          42895  529
Yes            26    0
is13_4_Yf      No  Yes
isCAM-dark
No          41994  497
Yes            21    0
is13_5_Ya      No  Yes
isCAM-dark
No          43314  110
Yes            26    0
is13_5_Yf      No  Yes
isCAM-dark
No          42392   99
Yes            21    0
is13_6_Ya      No  Yes
isCAM-dark
No          43276  148
Yes            26    0
is13_6_Yf      No  Yes
isCAM-dark
No          42359  132
Yes            21    0
is45_1_Ya      No  Yes
isCAM-dark
No          42514  910
Yes            25    1
is45_1_Yf      No  Yes
isCAM-dark
No          41612  879
Yes            21    0
is45_2_Ya      No   Yes
isCAM-dark
No          41382  2042
Yes            22     4
is45_2_Yf      No   Yes
isCAM-dark
No          40654  1837
Yes            20     1
is45_3_Ya      No  Yes
isCAM-dark
No          42631  793
Yes            26    0
is45_3_Yf      No  Yes
isCAM-dark
No          41742  749
Yes            21    0
is45_4_Ya      No   Yes
isCAM-dark
No          41687  1737
Yes            24     2
is45_4_Yf      No   Yes
isCAM-dark
No          40856  1635
Yes            20     1
is45_5_Ya      No  Yes
isCAM-dark
No          42482  942
Yes            25    1
is45_5_Yf      No  Yes
isCAM-dark
No          41640  851
Yes            20    1
is45_6_Ya      No   Yes
isCAM-dark
No          41520  1904
Yes            26     0
is45_6_Yf      No   Yes
isCAM-dark
No          40676  1815
Yes            20     1
is19_1_Ya      No  Yes
isCAM-dark
No          42667  757
Yes            24    2
is19_1_Yf      No  Yes
isCAM-dark
No          41878  613
Yes            20    1
is19_2_Ya      No  Yes
isCAM-dark
No          42743  681
Yes            26    0
is19_2_Yf      No  Yes
isCAM-dark
No          41896  595
Yes            21    0

is19_3_Ya      No   Yes
isCAM-dark
No          41958  1466
Yes            24     2
is19_3_Yf      No   Yes
isCAM-dark
No          41112  1379
Yes            20     1
is19_4_Ya      No   Yes
isCAM-dark
No          42370  1054
Yes            25     1
is19_4_Yf      No  Yes
isCAM-dark
No          41497  994
Yes            19    2
is19_5_Ya      No   Yes
isCAM-dark
No          42414  1010
Yes            25     1
is19_5_Yf      No  Yes
isCAM-dark
No          41521  970
Yes            20    1
is19_6_Ya      No  Yes
isCAM-dark
No          42641  783
Yes            26    0
is19_6_Yf      No  Yes
isCAM-dark
No          41776  715
Yes            21    0
is51_1_Ya      No   Yes
isCAM-dark
No          37500  5924
Yes            24     2
is51_1_Yf      No   Yes
isCAM-dark
No          36961  5530
Yes            21     0
is51_2_Ya      No   Yes
isCAM-dark
No          38381  5043
Yes            20     6
is51_2_Yf      No   Yes
isCAM-dark
No          37567  4924
Yes            18     3
is51_3_Ya      No   Yes
isCAM-dark
No          41059  2365
Yes            26     0
is51_3_Yf      No   Yes
isCAM-dark
No          40117  2374
Yes            20     1
is51_4_Ya      No   Yes
isCAM-dark
No          39142  4282
Yes            23     3
is51_4_Yf      No   Yes
isCAM-dark
No          38467  4024
Yes            17     4
is51_5_Ya      No   Yes
isCAM-dark
No          40923  2501
Yes            25     1
is51_5_Yf      No   Yes
isCAM-dark
No          40279  2212
Yes            21     0
is51_6_Ya      No   Yes
isCAM-dark
No          41889  1535
Yes            23     3
is51_6_Yf      No   Yes
isCAM-dark
No          41003  1488
Yes            16     5
is2AB_1_Ya     No   Yes
isCAM-dark
No          40009  3415
Yes            24     2
is2AB_1_Yf     No   Yes
isCAM-dark
No          39206  3285
Yes            19     2
is2AB_2_Ya     No   Yes
isCAM-dark
No          41421  2003
Yes            23     3
is2AB_2_Yf     No   Yes
isCAM-dark
No          40572  1919
Yes            17     4
is2AB_3_Ya     No   Yes
isCAM-dark
No          39047  4377
Yes            20     6
is2AB_3_Yf     No   Yes
isCAM-dark
No          38517  3974
Yes            18     3
is2AB_4_Ya     No   Yes
isCAM-dark
No          40819  2605
Yes            23     3
is2AB_4_Yf     No   Yes
isCAM-dark
No          40026  2465
Yes            20     1
is2AB_5_Ya     No   Yes
isCAM-dark
No          41919  1505
Yes            25     1
is2AB_5_Yf     No   Yes
isCAM-dark
No          41076  1415
Yes            19     2
is2AB_6_Ya     No   Yes
isCAM-dark
No          40649  2775
Yes            24     2
is2AB_6_Yf     No   Yes
isCAM-dark
No          39804  2687
Yes            20     1
is52_1_Ya      No  Yes
isCAM-dark
No          42729  695
Yes            24    2
is52_1_Yf      No  Yes
isCAM-dark
No          41873  618
Yes            21    0
is52_2_Ya      No  Yes
isCAM-dark
No          42625  799
Yes            26    0
is52_2_Yf      No  Yes
isCAM-dark
No          41683  808
Yes            21    0
is52_3_Ya      No  Yes
isCAM-dark
No          42744  680
Yes            25    1
is52_3_Yf      No  Yes
isCAM-dark
No          41814  677
Yes            21    0
is52_4_Ya      No  Yes
isCAM-dark
No          43017  407
Yes            26    0
is52_4_Yf      No  Yes
isCAM-dark
No          42118  373
Yes            21    0
is52_5_Ya      No  Yes
isCAM-dark
No          43094  330
Yes            26    0
is52_5_Yf      No  Yes
isCAM-dark
No          42192  299
Yes            21    0
is52_6_Ya      No  Yes
isCAM-dark
No          43176  248
Yes            26    0
is52_6_Yf      No  Yes
isCAM-dark
No          42251  240
Yes            20    1
is46_1_Ya      No   Yes
isCAM-dark
No          42061  1363
Yes            25     1
is46_1_Yf      No   Yes
isCAM-dark
No          41157  1334
Yes            20     1
is46_2_Ya      No  Yes
isCAM-dark
No          42484  940
Yes            26    0
is46_2_Yf      No  Yes
isCAM-dark
No          41574  917
Yes            21    0
is46_3_Ya      No   Yes
isCAM-dark
No          42369  1055
Yes            26     0
is46_3_Yf      No   Yes
isCAM-dark
No          41471  1020
Yes            20     1
is46_4_Ya      No  Yes
isCAM-dark
No          43036  388
Yes            26    0
is46_4_Yf      No  Yes
isCAM-dark
No          42130  361
Yes            21    0
is46_5_Ya      No  Yes
isCAM-dark
No          42447  977
Yes            25    1
is46_5_Yf      No  Yes
isCAM-dark
No          41648  843
Yes            21    0
is46_6_Ya      No   Yes
isCAM-dark
No          42292  1132
Yes            23     3
is46_6_Yf      No   Yes
isCAM-dark
No          41449  1042
Yes            20     1
is70_1_Ya      No   Yes
isCAM-dark
No          41122  2302
Yes            25     1
is70_1_Yf      No   Yes
isCAM-dark
No          40273  2218
Yes            21     0
is70_2_Ya      No   Yes
isCAM-dark
No          41950  1474
Yes            23     3
is70_2_Yf      No   Yes
isCAM-dark
No          41024  1467
Yes            20     1
is70_3_Ya      No   Yes
isCAM-dark
No          40520  2904
Yes            22     4
is70_3_Yf      No   Yes
isCAM-dark
No          39555  2936
Yes            19     2
is70_4_Ya      No   Yes
isCAM-dark
No          41986  1438
Yes            26     0
is70_4_Yf      No   Yes
isCAM-dark
No          41072  1419
Yes            21     0
is70_5_Ya      No   Yes
isCAM-dark
No          41344  2080
Yes            24     2
is70_5_Yf      No   Yes
isCAM-dark
No          40538  1953
Yes            19     2
is70_6_Ya      No   Yes
isCAM-dark
No          42184  1240
Yes            25     1
is70_6_Yf      No   Yes
isCAM-dark
No          41272  1219
Yes            20     1
is48_1_Ya      No  Yes
isCAM-dark
No          42765  659
Yes            26    0
is48_1_Yf      No  Yes
isCAM-dark
No          41821  670
Yes            20    1
is48_2_Ya      No  Yes
isCAM-dark
No          43129  295
Yes            26    0
is48_2_Yf      No  Yes
isCAM-dark
No          42252  239
Yes            21    0
is48_3_Ya      No  Yes
isCAM-dark
No          42480  944
Yes            26    0
is48_3_Yf      No  Yes
isCAM-dark
No          41531  960
Yes            21    0
is48_4_Ya      No  Yes
isCAM-dark
No          42681  743
Yes            26    0
is48_4_Yf      No  Yes
isCAM-dark
No          41803  688
Yes            21    0
is48_5_Ya      No  Yes
isCAM-dark
No          42844  580
Yes            23    3
is48_5_Yf      No  Yes
isCAM-dark
No          41911  580
Yes            21    0
is48_6_Ya      No  Yes
isCAM-dark
No          43133  291
Yes            26    0
is48_6_Yf      No  Yes
isCAM-dark
No          42182  309
Yes            20    1
is55_1_Ya      No   Yes
isCAM-dark
No          40772  2652
Yes            24     2
is55_1_Yf      No   Yes
isCAM-dark
No          40154  2337
Yes            20     1
is55_2_Ya      No   Yes
isCAM-dark
No          40701  2723
Yes            24     2
is55_2_Yf      No   Yes
isCAM-dark
No          39887  2604
Yes            19     2
is55_3_Ya      No   Yes
isCAM-dark
No          41437  1987
Yes            26     0
is55_3_Yf      No   Yes
isCAM-dark
No          40678  1813
Yes            21     0
is55_4_Ya      No   Yes
isCAM-dark
No          41793  1631
Yes            23     3

is55_4_Yf      No   Yes
isCAM-dark
No          41027  1464
Yes            20     1
is55_5_Ya      No   Yes
isCAM-dark
No          39311  4113
Yes            22     4
is55_5_Yf      No   Yes
isCAM-dark
No          38666  3825
Yes            21     0
is55_6_Ya      No   Yes
isCAM-dark
No          39959  3465
Yes            23     3
is55_6_Yf      No   Yes
isCAM-dark
No          39227  3264
Yes            19     2
is18_1_Ya      No   Yes
isCAM-dark
No          40879  2545
Yes            25     1
is18_1_Yf      No   Yes
isCAM-dark
No          40152  2339
Yes            21     0
is18_2_Ya      No   Yes
isCAM-dark
No          39949  3475
Yes            21     5
is18_2_Yf      No   Yes
isCAM-dark
No          39199  3292
Yes            18     3
is18_3_Ya      No   Yes
isCAM-dark
No          42413  1011
Yes            25     1
is18_3_Yf      No  Yes
isCAM-dark
No          41545  946
Yes            20    1
is18_4_Ya      No   Yes
isCAM-dark
No          41109  2315
Yes            24     2
is18_4_Yf      No   Yes
isCAM-dark
No          40180  2311
Yes            20     1
is18_5_Ya      No   Yes
isCAM-dark
No          40884  2540
Yes            26     0
is18_5_Yf      No   Yes
isCAM-dark
No          40068  2423
Yes            21     0
is18_6_Ya      No  Yes
isCAM-dark
No          42962  462
Yes            26    0
is18_6_Yf      No  Yes
isCAM-dark
No          42038  453
Yes            21    0
is61_1_Ya      No  Yes
isCAM-dark
No          42593  831
Yes            24    2
is61_1_Yf      No  Yes
isCAM-dark
No          41716  775
Yes            21    0
is61_2_Ya      No   Yes
isCAM-dark
No          38678  4746
Yes            21     5
is61_2_Yf      No   Yes
isCAM-dark
No          37741  4750
Yes            15     6
is61_3_Ya      No   Yes
isCAM-dark
No          41920  1504
Yes            26     0
is61_3_Yf      No   Yes
isCAM-dark
No          41111  1380
Yes            21     0
is61_4_Ya      No   Yes
isCAM-dark
No          41999  1425
Yes            25     1
is61_4_Yf      No   Yes
isCAM-dark
No          41060  1431
Yes            21     0
is61_5_Ya      No   Yes
isCAM-dark
No          40711  2713
Yes            20     6
is61_5_Yf      No   Yes
isCAM-dark
No          39950  2541
Yes            20     1
is61_6_Ya      No   Yes
isCAM-dark
No          41234  2190
Yes            24     2
is61_6_Yf      No   Yes
isCAM-dark
No          40430  2061
Yes            20     1
is53_1_Ya      No  Yes
isCAM-dark
No          43263  161
Yes            26    0
is53_1_Yf      No  Yes
isCAM-dark
No          42333  158
Yes            21    0
is53_2_Ya      No  Yes
isCAM-dark
No          43091  333
Yes            25    1
is53_2_Yf      No  Yes
isCAM-dark
No          42169  322
Yes            21    0
is53_3_Ya      No  Yes
isCAM-dark
No          42986  438
Yes            25    1
is53_3_Yf      No  Yes
isCAM-dark
No          42048  443
Yes            21    0
is53_4_Ya      No  Yes
isCAM-dark
No          42901  523
Yes            26    0
is53_4_Yf      No  Yes
isCAM-dark
No          41943  548
Yes            21    0
is53_5_Ya      No  Yes
isCAM-dark
No          43201  223
Yes            26    0
is53_5_Yf      No  Yes
isCAM-dark
No          42286  205
Yes            21    0
is53_6_Ya      No  Yes
isCAM-dark
No          43005  419
Yes            26    0
is53_6_Yf      No  Yes
isCAM-dark
No          42133  358
Yes            21    0
is56_1_Ya      No   Yes
isCAM-dark
No          42333  1091
Yes            26     0
is56_1_Yf      No  Yes
isCAM-dark
No          41539  952
Yes            20    1
is56_2_Ya      No   Yes
isCAM-dark
No          41536  1888
Yes            24     2
is56_2_Yf      No   Yes
isCAM-dark
No          40779  1712
Yes            21     0
is56_3_Ya      No   Yes
isCAM-dark
No          41767  1657
Yes            24     2
is56_3_Yf      No   Yes
isCAM-dark
No          40956  1535
Yes            17     4
is56_4_Ya      No   Yes
isCAM-dark
No          42120  1304
Yes            26     0
is56_4_Yf      No   Yes
isCAM-dark
No          41260  1231
Yes            21     0
is56_5_Ya      No  Yes
isCAM-dark
No          42966  458
Yes            25    1
is56_5_Yf      No  Yes
isCAM-dark
No          42036  455
Yes            20    1
is56_6_Ya      No  Yes
isCAM-dark
No          43063  361
Yes            26    0
is56_6_Yf      No  Yes
isCAM-dark
No          42144  347
Yes            21    0
is1AB_1_Ya     No  Yes
isCAM-dark
No          42721  703
Yes            25    1
is1AB_1_Yf     No  Yes
isCAM-dark
No          41786  705
Yes            20    1
is1AB_2_Ya     No   Yes
isCAM-dark
No          40909  2515
Yes            22     4
is1AB_2_Yf     No   Yes
isCAM-dark
No          40168  2323
Yes            17     4
is1AB_3_Ya     No   Yes
isCAM-dark
No          41222  2202
Yes            25     1
is1AB_3_Yf     No   Yes
isCAM-dark
No          40493  1998
Yes            19     2
is1AB_4_Ya     No   Yes
isCAM-dark
No          41985  1439
Yes            25     1
is1AB_4_Yf     No   Yes
isCAM-dark
No          41232  1259
Yes            21     0
is1AB_5_Ya     No   Yes
isCAM-dark
No          41473  1951
Yes            25     1
is1AB_5_Yf     No   Yes
isCAM-dark
No          40611  1880
Yes            19     2
is1AB_6_Ya     No   Yes
isCAM-dark
No          42279  1145
Yes            25     1
is1AB_6_Yf     No   Yes
isCAM-dark
No          41366  1125
Yes            19     2
is37_1_Ya      No   Yes
isCAM-dark
No          40802  2622
Yes            26     0
is37_1_Yf      No   Yes
isCAM-dark
No          39925  2566
Yes            21     0
is37_2_Ya      No   Yes
isCAM-dark
No          40089  3335
Yes            25     1
is37_2_Yf      No   Yes
isCAM-dark
No          39282  3209
Yes            18     3
is37_3_Ya      No   Yes
isCAM-dark
No          39121  4303
Yes            18     8
is37_3_Yf      No   Yes
isCAM-dark
No          38289  4202
Yes            17     4
is37_4_Ya      No   Yes
isCAM-dark
No          38240  5184
Yes            18     8
is37_4_Yf      No   Yes
isCAM-dark
No          37527  4964
Yes            19     2
is37_5_Ya      No   Yes
isCAM-dark
No          38774  4650
Yes            23     3
is37_5_Yf      No   Yes
isCAM-dark
No          37938  4553
Yes            20     1
is37_6_Ya      No   Yes
isCAM-dark
No          39906  3518
Yes            26     0
is37_6_Yf      No   Yes
isCAM-dark
No          39046  3445
Yes            19     2
is1.0          No    Yes
isCAM-dark
No          58809  27106
Yes            22     25
is9.0          No    Yes
isCAM-dark
No          51808  34107
Yes            20     27
is5.0          No    Yes
isCAM-dark
No          55259  30656
Yes            25     22
is21.0         No    Yes
isCAM-dark
No          57268  28647
Yes            27     20
is13.0         No    Yes
isCAM-dark
No          62751  23164
Yes            34     13
is17.0         No    Yes
isCAM-dark
No          57822  28093
Yes            27     20
is1.0_Ya       No    Yes
isCAM-dark
No          29893  13531
Yes            12     14
is1.0_Yf       No    Yes
isCAM-dark
No          28916  13575
Yes            10     11
is9.0_Ya       No    Yes
isCAM-dark
No          26350  17074
Yes            12     14

is9.0_Yf       No    Yes
isCAM-dark
No          25458  17033
Yes             8     13
is5.0_Ya       No    Yes
isCAM-dark
No          28081  15343
Yes            13     13
is5.0_Yf       No    Yes
isCAM-dark
No          27178  15313
Yes            12      9
is21.0_Ya      No    Yes
isCAM-dark
No          29131  14293
Yes            17      9
is21.0_Yf      No    Yes
isCAM-dark
No          28137  14354
Yes            10     11
is13.0_Ya      No    Yes
isCAM-dark
No          31576  11848
Yes            17      9
is13.0_Yf      No    Yes
isCAM-dark
No          31175  11316
Yes            17      4
is17.0_Ya      No    Yes
isCAM-dark
No          29131  14293
Yes            12     14
is17.0_Yf      No    Yes
isCAM-dark
No          28691  13800
Yes            15      6

In [167]:
lightres = test_enrichment(allgroups,"CAM-light")

isYa           No    Yes
isCAM-light
No           8664  34772
Yes             0     14
isYf           No    Yes
isCAM-light
No           8198  34305
Yes             1      8
isall           No    Yes
isCAM-light
No           16862  69077
Yes              1     22
isG             No   Yes
isCAM-light
No           82160  3779
Yes             19     4
isEudy          No   Yes
isCAM-light
No           77073  8866
Yes             18     5
is36            No    Yes
isCAM-light
No           59772  26167
Yes             11     12
is43            No    Yes
isCAM-light
No           47626  38313
Yes             10     13
is13            No   Yes
isCAM-light
No           82053  3886
Yes             19     4
is45            No    Yes
isCAM-light
No           69843  16096
Yes             13     10
is19            No    Yes
isCAM-light
No           74913  11026
Yes             21      2
is51            No    Yes
isCAM-light
No           43724  42215
Yes              8     15
is2AB           No    Yes
isCAM-light
No           53498  32441
Yes              9     14
is52            No   Yes
isCAM-light
No           79766  6173
Yes             18     5
is46            No    Yes
isCAM-light
No           74565  11374
Yes             17      6
is70            No    Yes
isCAM-light
No           63284  22655
Yes             11     12
is48            No   Yes
isCAM-light
No           78982  6957
Yes             17     6
is55            No    Yes
isCAM-light
No           54057  31882
Yes              7     16
is18            No    Yes
isCAM-light
No           61827  24112
Yes              9     14
is61            No    Yes
isCAM-light
No           59584  26355
Yes              7     16
is53            No   Yes
isCAM-light
No           81806  4133
Yes             23     0
is56            No    Yes
isCAM-light
No           72946  12993
Yes             14      9
is1AB           No    Yes
isCAM-light
No           66687  19252
Yes             10     13
is37            No    Yes
isCAM-light
No           39373  46566
Yes              6     17
isG_Ya          No   Yes
isCAM-light
No           41456  1980
Yes             11     3
isG_Yf          No   Yes
isCAM-light
No           40704  1799
Yes              8     1
isEudy_Ya       No   Yes
isCAM-light
No           38857  4579
Yes             10     4
isEudy_Yf       No   Yes
isCAM-light
No           38216  4287
Yes              8     1
is36_Ya         No    Yes
isCAM-light
No           30064  13372
Yes              5      9
is36_Yf         No    Yes
isCAM-light
No           29708  12795
Yes              6      3
is43_Ya         No    Yes
isCAM-light
No           24004  19432
Yes              4     10
is43_Yf         No    Yes
isCAM-light
No           23622  18881
Yes              6      3
is13_Ya         No   Yes
isCAM-light
No           41456  1980
Yes             11     3
is13_Yf         No   Yes
isCAM-light
No           40597  1906
Yes              8     1
is45_Ya         No   Yes
isCAM-light
No           35107  8329
Yes              7     7
is45_Yf         No   Yes
isCAM-light
No           34736  7767
Yes              6     3
is19_Ya         No   Yes
isCAM-light
No           37680  5756
Yes             13     1
is19_Yf         No   Yes
isCAM-light
No           37233  5270
Yes              8     1
is51_Ya         No    Yes
isCAM-light
No           21781  21655
Yes              4     10
is51_Yf         No    Yes
isCAM-light
No           21943  20560
Yes              4      5
is2AB_Ya        No    Yes
isCAM-light
No           26748  16688
Yes              5      9
is2AB_Yf        No    Yes
isCAM-light
No           26750  15753
Yes              4      5
is52_Ya         No   Yes
isCAM-light
No           40278  3158
Yes             10     4
is52_Yf         No   Yes
isCAM-light
No           39488  3015
Yes              8     1
is46_Ya         No   Yes
isCAM-light
No           37581  5855
Yes              9     5
is46_Yf         No   Yes
isCAM-light
No           36984  5519
Yes              8     1
is70_Ya         No    Yes
isCAM-light
No           31995  11441
Yes              6      8
is70_Yf         No    Yes
isCAM-light
No           31289  11214
Yes              5      4
is48_Ya         No   Yes
isCAM-light
No           39926  3510
Yes              9     5
is48_Yf         No   Yes
isCAM-light
No           39056  3447
Yes              8     1
is55_Ya         No    Yes
isCAM-light
No           26862  16574
Yes              3     11
is55_Yf         No    Yes
isCAM-light
No           27195  15308
Yes              4      5
is18_Ya         No    Yes
isCAM-light
No           31087  12349
Yes              6      8
is18_Yf         No    Yes
isCAM-light
No           30740  11763
Yes              3      6
is61_Ya         No    Yes
isCAM-light
No           30023  13413
Yes              2     12
is61_Yf         No    Yes
isCAM-light
No           29561  12942
Yes              5      4
is53_Ya         No   Yes
isCAM-light
No           41337  2099
Yes             14     0
is53_Yf         No   Yes
isCAM-light
No           40469  2034
Yes              9     0
is56_Ya         No   Yes
isCAM-light
No           36678  6758
Yes              8     6
is56_Yf         No   Yes
isCAM-light
No           36268  6235
Yes              6     3
is1AB_Ya        No   Yes
isCAM-light
No           33482  9954
Yes              4    10
is1AB_Yf        No   Yes
isCAM-light
No           33205  9298
Yes              6     3
is37_Ya         No    Yes
isCAM-light
No           19815  23621
Yes              3     11
is37_Yf         No    Yes
isCAM-light
No           19558  22945
Yes              3      6
isG_1           No  Yes
isCAM-light
No           84963  976
Yes             20    3
isG_2           No  Yes
isCAM-light
No           85025  914
Yes             23    0
isG_3           No  Yes
isCAM-light
No           85398  541
Yes             22    1
isG_4           No  Yes
isCAM-light
No           85317  622
Yes             23    0
isG_5           No  Yes
isCAM-light
No           85786  153
Yes             23    0
isG_6           No  Yes
isCAM-light
No           85366  573
Yes             23    0
isEudy_1        No   Yes
isCAM-light
No           84143  1796
Yes             23     0
isEudy_2        No   Yes
isCAM-light
No           84284  1655
Yes             23     0
isEudy_3        No   Yes
isCAM-light
No           84711  1228
Yes             22     1
isEudy_4        No   Yes
isCAM-light
No           83548  2391
Yes             19     4
isEudy_5        No  Yes
isCAM-light
No           84963  976
Yes             23    0
isEudy_6        No  Yes
isCAM-light
No           85119  820
Yes             23    0
is36_1          No   Yes
isCAM-light
No           78390  7549
Yes             19     4
is36_2          No   Yes
isCAM-light
No           80579  5360
Yes             22     1
is36_3          No   Yes
isCAM-light
No           83421  2518
Yes             23     0
is36_4          No   Yes
isCAM-light
No           81820  4119
Yes             18     5
is36_5          No   Yes
isCAM-light
No           83451  2488
Yes             23     0
is36_6          No   Yes
isCAM-light
No           81806  4133
Yes             21     2

is43_1          No   Yes
isCAM-light
No           82627  3312
Yes             21     2
is43_2          No   Yes
isCAM-light
No           77999  7940
Yes             21     2
is43_3          No    Yes
isCAM-light
No           74870  11069
Yes             22      1
is43_4          No   Yes
isCAM-light
No           80211  5728
Yes             20     3
is43_5          No   Yes
isCAM-light
No           79648  6291
Yes             20     3
is43_6          No   Yes
isCAM-light
No           81966  3973
Yes             21     2
is13_1          No  Yes
isCAM-light
No           85037  902
Yes             23    0
is13_2          No  Yes
isCAM-light
No           85143  796
Yes             22    1
is13_3          No  Yes
isCAM-light
No           85263  676
Yes             23    0
is13_4          No   Yes
isCAM-light
No           84916  1023
Yes             20     3
is13_5          No  Yes
isCAM-light
No           85730  209
Yes             23    0
is13_6          No  Yes
isCAM-light
No           85659  280
Yes             23    0
is45_1          No   Yes
isCAM-light
No           84154  1785
Yes             18     5
is45_2          No   Yes
isCAM-light
No           82057  3882
Yes             21     2
is45_3          No   Yes
isCAM-light
No           84397  1542
Yes             23     0
is45_4          No   Yes
isCAM-light
No           82566  3373
Yes             21     2
is45_5          No   Yes
isCAM-light
No           84145  1794
Yes             22     1
is45_6          No   Yes
isCAM-light
No           82219  3720
Yes             23     0
is19_1          No   Yes
isCAM-light
No           84566  1373
Yes             23     0
is19_2          No   Yes
isCAM-light
No           84663  1276
Yes             23     0
is19_3          No   Yes
isCAM-light
No           83093  2846
Yes             21     2
is19_4          No   Yes
isCAM-light
No           83888  2051
Yes             23     0
is19_5          No   Yes
isCAM-light
No           83957  1982
Yes             23     0
is19_6          No   Yes
isCAM-light
No           84441  1498
Yes             23     0
is51_1          No    Yes
isCAM-light
No           74484  11455
Yes             22      1
is51_2          No   Yes
isCAM-light
No           75966  9973
Yes             20     3
is51_3          No   Yes
isCAM-light
No           81201  4738
Yes             21     2
is51_4          No   Yes
isCAM-light
No           77631  8308
Yes             18     5
is51_5          No   Yes
isCAM-light
No           81226  4713
Yes             22     1
is51_6          No   Yes
isCAM-light
No           82911  3028
Yes             20     3
is2AB_1         No   Yes
isCAM-light
No           79239  6700
Yes             19     4
is2AB_2         No   Yes
isCAM-light
No           82012  3927
Yes             21     2
is2AB_3         No   Yes
isCAM-light
No           77583  8356
Yes             19     4
is2AB_4         No   Yes
isCAM-light
No           80868  5071
Yes             20     3
is2AB_5         No   Yes
isCAM-light
No           83017  2922
Yes             22     1
is2AB_6         No   Yes
isCAM-light
No           80474  5465
Yes             23     0
is52_1          No   Yes
isCAM-light
No           84626  1313
Yes             21     2
is52_2          No   Yes
isCAM-light
No           84332  1607
Yes             23     0
is52_3          No   Yes
isCAM-light
No           84584  1355
Yes             20     3
is52_4          No  Yes
isCAM-light
No           85159  780
Yes             23    0
is52_5          No  Yes
isCAM-light
No           85310  629
Yes             23    0
is52_6          No  Yes
isCAM-light
No           85450  489
Yes             23    0
is46_1          No   Yes
isCAM-light
No           83240  2699
Yes             23     0
is46_2          No   Yes
isCAM-light
No           84082  1857
Yes             23     0
is46_3          No   Yes
isCAM-light
No           83866  2073
Yes             20     3
is46_4          No  Yes
isCAM-light
No           85190  749
Yes             23    0
is46_5          No   Yes
isCAM-light
No           84119  1820
Yes             22     1
is46_6          No   Yes
isCAM-light
No           83763  2176
Yes             21     2
is70_1          No   Yes
isCAM-light
No           81418  4521
Yes             23     0
is70_2          No   Yes
isCAM-light
No           82995  2944
Yes             22     1
is70_3          No   Yes
isCAM-light
No           80098  5841
Yes             18     5
is70_4          No   Yes
isCAM-light
No           83082  2857
Yes             23     0
is70_5          No   Yes
isCAM-light
No           81907  4032
Yes             18     5
is70_6          No   Yes
isCAM-light
No           83479  2460
Yes             22     1
is48_1          No   Yes
isCAM-light
No           84610  1329
Yes             22     1
is48_2          No  Yes
isCAM-light
No           85405  534
Yes             23    0
is48_3          No   Yes
isCAM-light
No           84036  1903
Yes             22     1
is48_4          No   Yes
isCAM-light
No           84510  1429
Yes             21     2
is48_5          No   Yes
isCAM-light
No           84778  1161
Yes             21     2
is48_6          No  Yes
isCAM-light
No           85338  601
Yes             23    0
is55_1          No   Yes
isCAM-light
No           80948  4991
Yes             22     1
is55_2          No   Yes
isCAM-light
No           80615  5324
Yes             16     7
is55_3          No   Yes
isCAM-light
No           82139  3800
Yes             23     0
is55_4          No   Yes
isCAM-light
No           82840  3099
Yes             23     0
is55_5          No   Yes
isCAM-light
No           78005  7934
Yes             15     8
is55_6          No   Yes
isCAM-light
No           79205  6734
Yes             23     0
is18_1          No   Yes
isCAM-light
No           81056  4883
Yes             21     2
is18_2          No   Yes
isCAM-light
No           79166  6773
Yes             21     2
is18_3          No   Yes
isCAM-light
No           83980  1959
Yes             23     0
is18_4          No   Yes
isCAM-light
No           81315  4624
Yes             18     5
is18_5          No   Yes
isCAM-light
No           80981  4958
Yes             18     5
is18_6          No  Yes
isCAM-light
No           85024  915
Yes             23    0
is61_1          No   Yes
isCAM-light
No           84331  1608
Yes             23     0
is61_2          No   Yes
isCAM-light
No           76442  9497
Yes             13    10
is61_3          No   Yes
isCAM-light
No           83056  2883
Yes             22     1
is61_4          No   Yes
isCAM-light
No           83082  2857
Yes             23     0
is61_5          No   Yes
isCAM-light
No           80683  5256
Yes             18     5
is61_6          No   Yes
isCAM-light
No           81685  4254
Yes             23     0
is53_1          No  Yes
isCAM-light
No           85620  319
Yes             23    0
is53_2          No  Yes
isCAM-light
No           85283  656
Yes             23    0
is53_3          No  Yes
isCAM-light
No           85057  882
Yes             23    0
is53_4          No   Yes
isCAM-light
No           84868  1071
Yes             23     0
is53_5          No  Yes
isCAM-light
No           85511  428
Yes             23    0

is53_6          No  Yes
isCAM-light
No           85162  777
Yes             23    0
is56_1          No   Yes
isCAM-light
No           83896  2043
Yes             22     1
is56_2          No   Yes
isCAM-light
No           82337  3602
Yes             23     0
is56_3          No   Yes
isCAM-light
No           82746  3193
Yes             18     5
is56_4          No   Yes
isCAM-light
No           83407  2532
Yes             20     3
is56_5          No  Yes
isCAM-light
No           85024  915
Yes             23    0
is56_6          No  Yes
isCAM-light
No           85231  708
Yes             23    0
is1AB_1         No   Yes
isCAM-light
No           84529  1410
Yes             23     0
is1AB_2         No   Yes
isCAM-light
No           81098  4841
Yes             18     5
is1AB_3         No   Yes
isCAM-light
No           81740  4199
Yes             19     4
is1AB_4         No   Yes
isCAM-light
No           83241  2698
Yes             22     1
is1AB_5         No   Yes
isCAM-light
No           82106  3833
Yes             22     1
is1AB_6         No   Yes
isCAM-light
No           83668  2271
Yes             21     2
is37_1          No   Yes
isCAM-light
No           80751  5188
Yes             23     0
is37_2          No   Yes
isCAM-light
No           79394  6545
Yes             20     3
is37_3          No   Yes
isCAM-light
No           77428  8511
Yes             17     6
is37_4          No    Yes
isCAM-light
No           75786  10153
Yes             18      5
is37_5          No   Yes
isCAM-light
No           76732  9207
Yes             23     0
is37_6          No   Yes
isCAM-light
No           78977  6962
Yes             20     3
isG_1_Ya        No  Yes
isCAM-light
No           42903  533
Yes             12    2
isG_1_Yf        No  Yes
isCAM-light
No           42060  443
Yes              8    1
isG_2_Ya        No  Yes
isCAM-light
No           42945  491
Yes             14    0
isG_2_Yf        No  Yes
isCAM-light
No           42080  423
Yes              9    0
isG_3_Ya        No  Yes
isCAM-light
No           43161  275
Yes             13    1
isG_3_Yf        No  Yes
isCAM-light
No           42237  266
Yes              9    0
isG_4_Ya        No  Yes
isCAM-light
No           43117  319
Yes             14    0
isG_4_Yf        No  Yes
isCAM-light
No           42200  303
Yes              9    0
isG_5_Ya        No  Yes
isCAM-light
No           43361   75
Yes             14    0
isG_5_Yf        No  Yes
isCAM-light
No           42425   78
Yes              9    0
isG_6_Ya        No  Yes
isCAM-light
No           43149  287
Yes             14    0
isG_6_Yf        No  Yes
isCAM-light
No           42217  286
Yes              9    0
isEudy_1_Ya     No  Yes
isCAM-light
No           42470  966
Yes             14    0
isEudy_1_Yf     No  Yes
isCAM-light
No           41673  830
Yes              9    0
isEudy_2_Ya     No  Yes
isCAM-light
No           42597  839
Yes             14    0
isEudy_2_Yf     No  Yes
isCAM-light
No           41687  816
Yes              9    0
isEudy_3_Ya     No  Yes
isCAM-light
No           42794  642
Yes             13    1
isEudy_3_Yf     No  Yes
isCAM-light
No           41917  586
Yes              9    0
isEudy_4_Ya     No   Yes
isCAM-light
No           42207  1229
Yes             11     3
isEudy_4_Yf     No   Yes
isCAM-light
No           41341  1162
Yes              8     1
isEudy_5_Ya     No  Yes
isCAM-light
No           42960  476
Yes             14    0
isEudy_5_Yf     No  Yes
isCAM-light
No           42003  500
Yes              9    0
isEudy_6_Ya     No  Yes
isCAM-light
No           43009  427
Yes             14    0
isEudy_6_Yf     No  Yes
isCAM-light
No           42110  393
Yes              9    0
is36_1_Ya       No   Yes
isCAM-light
No           39546  3890
Yes             11     3
is36_1_Yf       No   Yes
isCAM-light
No           38844  3659
Yes              8     1
is36_2_Ya       No   Yes
isCAM-light
No           40653  2783
Yes             14     0
is36_2_Yf       No   Yes
isCAM-light
No           39926  2577
Yes              8     1
is36_3_Ya       No   Yes
isCAM-light
No           42169  1267
Yes             14     0
is36_3_Yf       No   Yes
isCAM-light
No           41252  1251
Yes              9     0
is36_4_Ya       No   Yes
isCAM-light
No           41316  2120
Yes             10     4
is36_4_Yf       No   Yes
isCAM-light
No           40504  1999
Yes              8     1
is36_5_Ya       No   Yes
isCAM-light
No           42191  1245
Yes             14     0
is36_5_Yf       No   Yes
isCAM-light
No           41260  1243
Yes              9     0
is36_6_Ya       No   Yes
isCAM-light
No           41369  2067
Yes             12     2
is36_6_Yf       No   Yes
isCAM-light
No           40437  2066
Yes              9     0
is43_1_Ya       No   Yes
isCAM-light
No           41756  1680
Yes             12     2
is43_1_Yf       No   Yes
isCAM-light
No           40871  1632
Yes              9     0
is43_2_Ya       No   Yes
isCAM-light
No           39411  4025
Yes             13     1
is43_2_Yf       No   Yes
isCAM-light
No           38588  3915
Yes              8     1
is43_3_Ya       No   Yes
isCAM-light
No           37832  5604
Yes             13     1
is43_3_Yf       No   Yes
isCAM-light
No           37038  5465
Yes              9     0
is43_4_Ya       No   Yes
isCAM-light
No           40477  2959
Yes             11     3
is43_4_Yf       No   Yes
isCAM-light
No           39734  2769
Yes              9     0
is43_5_Ya       No   Yes
isCAM-light
No           40291  3145
Yes             13     1
is43_5_Yf       No   Yes
isCAM-light
No           39357  3146
Yes              7     2
is43_6_Ya       No   Yes
isCAM-light
No           41417  2019
Yes             12     2
is43_6_Yf       No   Yes
isCAM-light
No           40549  1954
Yes              9     0
is13_1_Ya       No  Yes
isCAM-light
No           42973  463
Yes             14    0
is13_1_Yf       No  Yes
isCAM-light
No           42064  439
Yes              9    0
is13_2_Ya       No  Yes
isCAM-light
No           43045  391
Yes             13    1
is13_2_Yf       No  Yes
isCAM-light
No           42098  405
Yes              9    0
is13_3_Ya       No  Yes
isCAM-light
No           43095  341
Yes             14    0
is13_3_Yf       No  Yes
isCAM-light
No           42168  335
Yes              9    0
is13_4_Ya       No  Yes
isCAM-light
No           42909  527
Yes             12    2
is13_4_Yf       No  Yes
isCAM-light
No           42007  496
Yes              8    1
is13_5_Ya       No  Yes
isCAM-light
No           43326  110
Yes             14    0
is13_5_Yf       No  Yes
isCAM-light
No           42404   99
Yes              9    0
is13_6_Ya       No  Yes
isCAM-light
No           43288  148
Yes             14    0
is13_6_Yf       No  Yes
isCAM-light
No           42371  132
Yes              9    0
is45_1_Ya       No  Yes
isCAM-light
No           42528  908
Yes             11    3
is45_1_Yf       No  Yes
isCAM-light
No           41626  877
Yes              7    2
is45_2_Ya       No   Yes
isCAM-light
No           41392  2044
Yes             12     2
is45_2_Yf       No   Yes
isCAM-light
No           40665  1838
Yes              9     0
is45_3_Ya       No  Yes
isCAM-light
No           42643  793
Yes             14    0

is45_3_Yf       No  Yes
isCAM-light
No           41754  749
Yes              9    0
is45_4_Ya       No   Yes
isCAM-light
No           41698  1738
Yes             13     1
is45_4_Yf       No   Yes
isCAM-light
No           40868  1635
Yes              8     1
is45_5_Ya       No  Yes
isCAM-light
No           42494  942
Yes             13    1
is45_5_Yf       No  Yes
isCAM-light
No           41651  852
Yes              9    0
is45_6_Ya       No   Yes
isCAM-light
No           41532  1904
Yes             14     0
is45_6_Yf       No   Yes
isCAM-light
No           40687  1816
Yes              9     0
is19_1_Ya       No  Yes
isCAM-light
No           42677  759
Yes             14    0
is19_1_Yf       No  Yes
isCAM-light
No           41889  614
Yes              9    0
is19_2_Ya       No  Yes
isCAM-light
No           42755  681
Yes             14    0
is19_2_Yf       No  Yes
isCAM-light
No           41908  595
Yes              9    0
is19_3_Ya       No   Yes
isCAM-light
No           41969  1467
Yes             13     1
is19_3_Yf       No   Yes
isCAM-light
No           41124  1379
Yes              8     1
is19_4_Ya       No   Yes
isCAM-light
No           42381  1055
Yes             14     0
is19_4_Yf       No  Yes
isCAM-light
No           41507  996
Yes              9    0
is19_5_Ya       No   Yes
isCAM-light
No           42425  1011
Yes             14     0
is19_5_Yf       No  Yes
isCAM-light
No           41532  971
Yes              9    0
is19_6_Ya       No  Yes
isCAM-light
No           42653  783
Yes             14    0
is19_6_Yf       No  Yes
isCAM-light
No           41788  715
Yes              9    0
is51_1_Ya       No   Yes
isCAM-light
No           37511  5925
Yes             13     1
is51_1_Yf       No   Yes
isCAM-light
No           36973  5530
Yes              9     0
is51_2_Ya       No   Yes
isCAM-light
No           38388  5048
Yes             13     1
is51_2_Yf       No   Yes
isCAM-light
No           37578  4925
Yes              7     2
is51_3_Ya       No   Yes
isCAM-light
No           41073  2363
Yes             12     2
is51_3_Yf       No   Yes
isCAM-light
No           40128  2375
Yes              9     0
is51_4_Ya       No   Yes
isCAM-light
No           39154  4282
Yes             11     3
is51_4_Yf       No   Yes
isCAM-light
No           38477  4026
Yes              7     2
is51_5_Ya       No   Yes
isCAM-light
No           40935  2501
Yes             13     1
is51_5_Yf       No   Yes
isCAM-light
No           40291  2212
Yes              9     0
is51_6_Ya       No   Yes
isCAM-light
No           41900  1536
Yes             12     2
is51_6_Yf       No   Yes
isCAM-light
No           41011  1492
Yes              8     1
is2AB_1_Ya      No   Yes
isCAM-light
No           40023  3413
Yes             10     4
is2AB_1_Yf      No   Yes
isCAM-light
No           39216  3287
Yes              9     0
is2AB_2_Ya      No   Yes
isCAM-light
No           41430  2006
Yes             14     0
is2AB_2_Yf      No   Yes
isCAM-light
No           40582  1921
Yes              7     2
is2AB_3_Ya      No   Yes
isCAM-light
No           39056  4380
Yes             11     3
is2AB_3_Yf      No   Yes
isCAM-light
No           38527  3976
Yes              8     1
is2AB_4_Ya      No   Yes
isCAM-light
No           40829  2607
Yes             13     1
is2AB_4_Yf      No   Yes
isCAM-light
No           40039  2464
Yes              7     2
is2AB_5_Ya      No   Yes
isCAM-light
No           41931  1505
Yes             13     1
is2AB_5_Yf      No   Yes
isCAM-light
No           41086  1417
Yes              9     0
is2AB_6_Ya      No   Yes
isCAM-light
No           40659  2777
Yes             14     0
is2AB_6_Yf      No   Yes
isCAM-light
No           39815  2688
Yes              9     0
is52_1_Ya       No  Yes
isCAM-light
No           42741  695
Yes             12    2
is52_1_Yf       No  Yes
isCAM-light
No           41885  618
Yes              9    0
is52_2_Ya       No  Yes
isCAM-light
No           42637  799
Yes             14    0
is52_2_Yf       No  Yes
isCAM-light
No           41695  808
Yes              9    0
is52_3_Ya       No  Yes
isCAM-light
No           42757  679
Yes             12    2
is52_3_Yf       No  Yes
isCAM-light
No           41827  676
Yes              8    1
is52_4_Ya       No  Yes
isCAM-light
No           43029  407
Yes             14    0
is52_4_Yf       No  Yes
isCAM-light
No           42130  373
Yes              9    0
is52_5_Ya       No  Yes
isCAM-light
No           43106  330
Yes             14    0
is52_5_Yf       No  Yes
isCAM-light
No           42204  299
Yes              9    0
is52_6_Ya       No  Yes
isCAM-light
No           43188  248
Yes             14    0
is52_6_Yf       No  Yes
isCAM-light
No           42262  241
Yes              9    0
is46_1_Ya       No   Yes
isCAM-light
No           42072  1364
Yes             14     0
is46_1_Yf       No   Yes
isCAM-light
No           41168  1335
Yes              9     0
is46_2_Ya       No  Yes
isCAM-light
No           42496  940
Yes             14    0
is46_2_Yf       No  Yes
isCAM-light
No           41586  917
Yes              9    0
is46_3_Ya       No   Yes
isCAM-light
No           42383  1053
Yes             12     2
is46_3_Yf       No   Yes
isCAM-light
No           41483  1020
Yes              8     1
is46_4_Ya       No  Yes
isCAM-light
No           43048  388
Yes             14    0
is46_4_Yf       No  Yes
isCAM-light
No           42142  361
Yes              9    0
is46_5_Ya       No  Yes
isCAM-light
No           42459  977
Yes             13    1
is46_5_Yf       No  Yes
isCAM-light
No           41660  843
Yes              9    0
is46_6_Ya       No   Yes
isCAM-light
No           42303  1133
Yes             12     2
is46_6_Yf       No   Yes
isCAM-light
No           41460  1043
Yes              9     0
is70_1_Ya       No   Yes
isCAM-light
No           41133  2303
Yes             14     0
is70_1_Yf       No   Yes
isCAM-light
No           40285  2218
Yes              9     0
is70_2_Ya       No   Yes
isCAM-light
No           41959  1477
Yes             14     0
is70_2_Yf       No   Yes
isCAM-light
No           41036  1467
Yes              8     1
is70_3_Ya       No   Yes
isCAM-light
No           40532  2904
Yes             10     4
is70_3_Yf       No   Yes
isCAM-light
No           39566  2937
Yes              8     1
is70_4_Ya       No   Yes
isCAM-light
No           41998  1438
Yes             14     0
is70_4_Yf       No   Yes
isCAM-light
No           41084  1419
Yes              9     0
is70_5_Ya       No   Yes
isCAM-light
No           41357  2079
Yes             11     3
is70_5_Yf       No   Yes
isCAM-light
No           40550  1953
Yes              7     2
is70_6_Ya       No   Yes
isCAM-light
No           42196  1240
Yes             13     1
is70_6_Yf       No   Yes
isCAM-light
No           41283  1220
Yes              9     0
is48_1_Ya       No  Yes
isCAM-light
No           42778  658
Yes             13    1
is48_1_Yf       No  Yes
isCAM-light
No           41832  671
Yes              9    0
is48_2_Ya       No  Yes
isCAM-light
No           43141  295
Yes             14    0
is48_2_Yf       No  Yes
isCAM-light
No           42264  239
Yes              9    0
is48_3_Ya       No  Yes
isCAM-light
No           42493  943
Yes             13    1

is48_3_Yf       No  Yes
isCAM-light
No           41543  960
Yes              9    0
is48_4_Ya       No  Yes
isCAM-light
No           42695  741
Yes             12    2
is48_4_Yf       No  Yes
isCAM-light
No           41815  688
Yes              9    0
is48_5_Ya       No  Yes
isCAM-light
No           42854  582
Yes             13    1
is48_5_Yf       No  Yes
isCAM-light
No           41924  579
Yes              8    1
is48_6_Ya       No  Yes
isCAM-light
No           43145  291
Yes             14    0
is48_6_Yf       No  Yes
isCAM-light
No           42193  310
Yes              9    0
is55_1_Ya       No   Yes
isCAM-light
No           40782  2654
Yes             14     0
is55_1_Yf       No   Yes
isCAM-light
No           40166  2337
Yes              8     1
is55_2_Ya       No   Yes
isCAM-light
No           40716  2720
Yes              9     5
is55_2_Yf       No   Yes
isCAM-light
No           39899  2604
Yes              7     2
is55_3_Ya       No   Yes
isCAM-light
No           41449  1987
Yes             14     0
is55_3_Yf       No   Yes
isCAM-light
No           40690  1813
Yes              9     0
is55_4_Ya       No   Yes
isCAM-light
No           41802  1634
Yes             14     0
is55_4_Yf       No   Yes
isCAM-light
No           41038  1465
Yes              9     0
is55_5_Ya       No   Yes
isCAM-light
No           39325  4111
Yes              8     6
is55_5_Yf       No   Yes
isCAM-light
No           38680  3823
Yes              7     2
is55_6_Ya       No   Yes
isCAM-light
No           39968  3468
Yes             14     0
is55_6_Yf       No   Yes
isCAM-light
No           39237  3266
Yes              9     0
is18_1_Ya       No   Yes
isCAM-light
No           40891  2545
Yes             13     1
is18_1_Yf       No   Yes
isCAM-light
No           40165  2338
Yes              8     1
is18_2_Ya       No   Yes
isCAM-light
No           39957  3479
Yes             13     1
is18_2_Yf       No   Yes
isCAM-light
No           39209  3294
Yes              8     1
is18_3_Ya       No   Yes
isCAM-light
No           42424  1012
Yes             14     0
is18_3_Yf       No  Yes
isCAM-light
No           41556  947
Yes              9    0
is18_4_Ya       No   Yes
isCAM-light
No           41122  2314
Yes             11     3
is18_4_Yf       No   Yes
isCAM-light
No           40193  2310
Yes              7     2
is18_5_Ya       No   Yes
isCAM-light
No           40899  2537
Yes             11     3
is18_5_Yf       No   Yes
isCAM-light
No           40082  2421
Yes              7     2
is18_6_Ya       No  Yes
isCAM-light
No           42974  462
Yes             14    0
is18_6_Yf       No  Yes
isCAM-light
No           42050  453
Yes              9    0
is61_1_Ya       No  Yes
isCAM-light
No           42603  833
Yes             14    0
is61_1_Yf       No  Yes
isCAM-light
No           41728  775
Yes              9    0
is61_2_Ya       No   Yes
isCAM-light
No           38693  4743
Yes              6     8
is61_2_Yf       No   Yes
isCAM-light
No           37749  4754
Yes              7     2
is61_3_Ya       No   Yes
isCAM-light
No           41933  1503
Yes             13     1
is61_3_Yf       No   Yes
isCAM-light
No           41123  1380
Yes              9     0
is61_4_Ya       No   Yes
isCAM-light
No           42010  1426
Yes             14     0
is61_4_Yf       No   Yes
isCAM-light
No           41072  1431
Yes              9     0
is61_5_Ya       No   Yes
isCAM-light
No           40720  2716
Yes             11     3
is61_5_Yf       No   Yes
isCAM-light
No           39963  2540
Yes              7     2
is61_6_Ya       No   Yes
isCAM-light
No           41244  2192
Yes             14     0
is61_6_Yf       No   Yes
isCAM-light
No           40441  2062
Yes              9     0
is53_1_Ya       No  Yes
isCAM-light
No           43275  161
Yes             14    0
is53_1_Yf       No  Yes
isCAM-light
No           42345  158
Yes              9    0
is53_2_Ya       No  Yes
isCAM-light
No           43102  334
Yes             14    0
is53_2_Yf       No  Yes
isCAM-light
No           42181  322
Yes              9    0
is53_3_Ya       No  Yes
isCAM-light
No           42997  439
Yes             14    0
is53_3_Yf       No  Yes
isCAM-light
No           42060  443
Yes              9    0
is53_4_Ya       No  Yes
isCAM-light
No           42913  523
Yes             14    0
is53_4_Yf       No  Yes
isCAM-light
No           41955  548
Yes              9    0
is53_5_Ya       No  Yes
isCAM-light
No           43213  223
Yes             14    0
is53_5_Yf       No  Yes
isCAM-light
No           42298  205
Yes              9    0
is53_6_Ya       No  Yes
isCAM-light
No           43017  419
Yes             14    0
is53_6_Yf       No  Yes
isCAM-light
No           42145  358
Yes              9    0
is56_1_Ya       No   Yes
isCAM-light
No           42346  1090
Yes             13     1
is56_1_Yf       No  Yes
isCAM-light
No           41550  953
Yes              9    0
is56_2_Ya       No   Yes
isCAM-light
No           41546  1890
Yes             14     0
is56_2_Yf       No   Yes
isCAM-light
No           40791  1712
Yes              9     0
is56_3_Ya       No   Yes
isCAM-light
No           41780  1656
Yes             11     3
is56_3_Yf       No   Yes
isCAM-light
No           40966  1537
Yes              7     2
is56_4_Ya       No   Yes
isCAM-light
No           42134  1302
Yes             12     2
is56_4_Yf       No   Yes
isCAM-light
No           41273  1230
Yes              8     1
is56_5_Ya       No  Yes
isCAM-light
No           42977  459
Yes             14    0
is56_5_Yf       No  Yes
isCAM-light
No           42047  456
Yes              9    0
is56_6_Ya       No  Yes
isCAM-light
No           43075  361
Yes             14    0
is56_6_Yf       No  Yes
isCAM-light
No           42156  347
Yes              9    0
is1AB_1_Ya      No  Yes
isCAM-light
No           42732  704
Yes             14    0
is1AB_1_Yf      No  Yes
isCAM-light
No           41797  706
Yes              9    0
is1AB_2_Ya      No   Yes
isCAM-light
No           40922  2514
Yes              9     5
is1AB_2_Yf      No   Yes
isCAM-light
No           40176  2327
Yes              9     0
is1AB_3_Ya      No   Yes
isCAM-light
No           41236  2200
Yes             11     3
is1AB_3_Yf      No   Yes
isCAM-light
No           40504  1999
Yes              8     1
is1AB_4_Ya      No   Yes
isCAM-light
No           41996  1440
Yes             14     0
is1AB_4_Yf      No   Yes
isCAM-light
No           41245  1258
Yes              8     1
is1AB_5_Ya      No   Yes
isCAM-light
No           41485  1951
Yes             13     1
is1AB_5_Yf      No   Yes
isCAM-light
No           40621  1882
Yes              9     0
is1AB_6_Ya      No   Yes
isCAM-light
No           42291  1145
Yes             13     1
is1AB_6_Yf      No   Yes
isCAM-light
No           41377  1126
Yes              8     1
is37_1_Ya       No   Yes
isCAM-light
No           40814  2622
Yes             14     0
is37_1_Yf       No   Yes
isCAM-light
No           39937  2566
Yes              9     0
is37_2_Ya       No   Yes
isCAM-light
No           40102  3334
Yes             12     2
is37_2_Yf       No   Yes
isCAM-light
No           39292  3211
Yes              8     1
is37_3_Ya       No   Yes
isCAM-light
No           39130  4306
Yes              9     5

is37_3_Yf       No   Yes
isCAM-light
No           38298  4205
Yes              8     1
is37_4_Ya       No   Yes
isCAM-light
No           38246  5190
Yes             12     2
is37_4_Yf       No   Yes
isCAM-light
No           37540  4963
Yes              6     3
is37_5_Ya       No   Yes
isCAM-light
No           38783  4653
Yes             14     0
is37_5_Yf       No   Yes
isCAM-light
No           37949  4554
Yes              9     0
is37_6_Ya       No   Yes
isCAM-light
No           39920  3516
Yes             12     2
is37_6_Yf       No   Yes
isCAM-light
No           39057  3446
Yes              8     1
is1.0           No    Yes
isCAM-light
No           58821  27118
Yes             10     13
is9.0           No    Yes
isCAM-light
No           51820  34119
Yes              8     15
is5.0           No    Yes
isCAM-light
No           55280  30659
Yes              4     19
is21.0          No    Yes
isCAM-light
No           57278  28661
Yes             17      6
is13.0          No    Yes
isCAM-light
No           62768  23171
Yes             17      6
is17.0          No    Yes
isCAM-light
No           57831  28108
Yes             18      5
is1.0_Ya        No    Yes
isCAM-light
No           29899  13537
Yes              6      8
is1.0_Yf        No    Yes
isCAM-light
No           28922  13581
Yes              4      5
is9.0_Ya        No    Yes
isCAM-light
No           26359  17077
Yes              3     11
is9.0_Yf        No    Yes
isCAM-light
No           25461  17042
Yes              5      4
is5.0_Ya        No    Yes
isCAM-light
No           28093  15343
Yes              1     13
is5.0_Yf        No    Yes
isCAM-light
No           27187  15316
Yes              3      6
is21.0_Ya       No    Yes
isCAM-light
No           29139  14297
Yes              9      5
is21.0_Yf       No    Yes
isCAM-light
No           28139  14364
Yes              8      1
is13.0_Ya       No    Yes
isCAM-light
No           31582  11854
Yes             11      3
is13.0_Yf       No    Yes
isCAM-light
No           31186  11317
Yes              6      3
is17.0_Ya       No    Yes
isCAM-light
No           29133  14303
Yes             10      4
is17.0_Yf       No    Yes
isCAM-light
No           28698  13805
Yes              8      1

In [168]:
darkres.head()

  Group   P-value  Odds Ratio     P-adj
0    Ya  0.005350         inf  0.117970
1    Yf  0.405184    2.270703  0.926694
2   all  0.005007    5.493853  0.117970
3     G  0.000945    4.463372  0.084081
4  Eudy  0.230351    0.386094  0.751373

In [170]:
allres.drop("P-adj_highN",axis=1,inplace=True)

In [171]:
allres["CAM_set"] = "all"
darkres["CAM_set"] = "dark"
lightres["CAM_set"] = "light"

In [172]:
camenrich = pd.concat([allres,darkres,lightres])
len(camenrich.index)

1323

In [174]:
# re-calculate FDR for everything all together
camenrich["P-adj_highN"] = fdrcorrection(camenrich["P-value"])[1]
camenrich.head()

  Group   P-value  Odds Ratio     P-adj CAM_set  P-adj_highN
0    Ya  0.000217         inf  0.000613     all     0.011533
1    Yf  0.250692    2.151432  0.250692     all     0.710114
2   all  0.000408    5.454572  0.000613     all     0.017427
0   1.0  0.000088    2.577190  0.001061     all     0.007789
1   9.0  0.000832    2.279127  0.003746     all     0.028478

In [178]:
# add other useful columns: subgenome & group type
subg = []
grptype = []
for i in list(camenrich["Group"]):
    if "Ya" in i:
        subg.append("Ya")
    elif "Yf" in i:
        subg.append("Yf")
    else:
        subg.append("both")
    
    if i in sg:
        grptype.append("overall_TSgenes")
    elif i in gtlist:
        grptype.append("genotype_TSgenes")
    elif i in ztplist:
        grptype.append("ZTpeak_clustergroup")
    elif i in gtclist:
        grptype.append("individual_cluster")
        
camenrich["subgenome"] = subg
camenrich["group_type"] = grptype

In [179]:
camsig = camenrich[camenrich["P-adj_highN"]<0.05]
len(camsig.index)

57

In [180]:
camsig.tail()

,Group,P-value,Odds Ratio,P-adj,CAM_set,P-adj_highN,subgenome,group_type
347,55_5_Ya,0.001106,7.174349,0.037522,light,0.032519,Ya,individual_cluster
365,61_2_Ya,0.000033,10.877223,0.003873,light,0.004647,Ya,individual_cluster
401,1AB_2_Ya,0.000839,9.043136,0.030851,light,0.028478,Ya,individual_cluster
425,5.0,0.000005,8.564532,0.002348,light,0.001912,both,ZTpeak_clustergroup
433,5.0_Ya,0.000013,23.802972,0.002775,light,0.003066,Ya,ZTpeak_clustergroup

In [183]:
# save both camenrich and camsig (overwrite previous files)
camenrich.to_csv("./camenrich_tsgenes_allp.txt",sep="\t",header=True,index=False)
camsig.to_csv("./camenrich_tsgenes_sigp.txt",sep="\t",header=True,index=False)

In [181]:
camsig[camsig["CAM_set"]=="light"]

,Group,P-value,Odds Ratio,P-adj,CAM_set,P-adj_highN,subgenome,group_type
16,55,0.001939,3.875505,0.050302,light,0.048096,both,genotype_TSgenes
17,18,0.001532,3.988692,0.042213,light,0.041352,both,genotype_TSgenes
18,61,0.000140,5.167596,0.008719,light,0.009290,both,genotype_TSgenes
21,1AB,0.000405,4.503070,0.017875,light,0.017427,both,genotype_TSgenes
53,61_Ya,0.000035,13.430105,0.003873,light,0.004647,Ya,genotype_TSgenes
59,1AB_Ya,0.000158,8.409182,0.008719,light,0.009964,Ya,genotype_TSgenes
93,45_1,0.000096,13.095861,0.007043,light,0.007923,both,individual_cluster
142,55_2,0.000356,6.624542,0.017425,light,0.017427,both,individual_cluster
145,55_5,0.000726,5.243593,0.029121,light,0.025973,both,individual_cluster
154,61_2,0.000079,6.191591,0.007006,light,0.007634,both,individual_cluster
167,56_3,0.001364,7.198559,0.040091,light,0.037585,both,individual_cluster
341,55_2_Ya,0.001199,8.316176,0.037766,light,0.034482,Ya,individual_cluster
347,55_5_Ya,0.001106,7.174349,0.037522,light,0.032519,Ya,individual_cluster
365,61_2_Ya,0.000033,10.877223,0.003873,light,0.004647,Ya,individual_cluster
401,1AB_2_Ya,0.000839,9.043136,0.030851,light,0.028478,Ya,individual_cluster
425,5.0,0.000005,8.564532,0.002348,light,0.001912,both,ZTpeak_clustergroup
433,5.0_Ya,0.000013,23.802972,0.002775,light,0.003066,Ya,ZTpeak_clustergroup

In [182]:
camsig[camsig["CAM_set"]=="dark"]

,Group,P-value,Odds Ratio,P-adj,CAM_set,P-adj_highN,subgenome,group_type
3,G,0.000945,4.463372,0.084081,dark,0.029331,both,genotype_TSgenes
11,2AB,0.000403,2.911152,0.084081,dark,0.017427,both,genotype_TSgenes
53,61_Ya,0.002056,3.581475,0.098278,dark,0.048567,Ya,genotype_TSgenes
60,1AB_Yf,0.002107,3.931227,0.098278,dark,0.048915,Yf,genotype_TSgenes
64,G_2,0.001575,8.689497,0.098278,dark,0.041686,both,individual_cluster
88,13_2,0.000953,9.985278,0.084081,dark,0.029331,both,individual_cluster
110,51_6,0.000218,5.624706,0.084081,dark,0.011533,both,individual_cluster
179,37_3,0.001692,3.120585,0.098278,dark,0.043900,both,individual_cluster
278,51_6_Yf,0.000675,8.611181,0.084081,dark,0.024795,Yf,individual_cluster

In [184]:
# make a nice summary table of genotype results (with FDR p-values)
gttab = camsig[camsig["group_type"]=="genotype_TSgenes"]

In [187]:
gttab.head()

,Genotype,P-value,Odds Ratio,P-adj,CAM_set,P-adj_highN,subgenome,group_type
0,G,0.000051,4.505583,0.000614,all,0.005853,both,genotype_TSgenes
8,2AB,0.000032,2.792457,0.000481,all,0.004647,both,genotype_TSgenes
15,61,0.000006,3.016014,0.000116,all,0.001912,both,genotype_TSgenes
18,1AB,0.000005,3.091385,0.000116,all,0.001912,both,genotype_TSgenes
20,G_Ya,0.000386,5.244937,0.003858,all,0.017427,Ya,genotype_TSgenes

In [186]:
gttab.rename(columns={"Group":"Genotype"},inplace=True)

/tmp/ipykernel_140/1404136697.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gttab.rename(columns={"Group":"Genotype"},inplace=True)

In [188]:
gttab.drop(["P-value","Odds Ratio","P-adj","group_type"],axis=1,inplace=True)
gttab.rename(columns={"P-adj-highN":"P-adj"},inplace=True)

/tmp/ipykernel_140/231369202.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gttab.drop(["P-value","Odds Ratio","P-adj","group_type"],axis=1,inplace=True)
/tmp/ipykernel_140/231369202.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gttab.rename(columns={"P-adj-highN":"P-adj"},inplace=True)

In [189]:
gttab.head()

   Genotype CAM_set  P-adj_highN subgenome
0         G     all     0.005853      both
8       2AB     all     0.004647      both
15       61     all     0.001912      both
18      1AB     all     0.001912      both
20     G_Ya     all     0.017427        Ya

In [190]:
for i in list(gttab["Genotype"]):
    if "_" in i:
        gttab["Genotype"].replace(i,i.split("_")[0],inplace=True)

/tmp/ipykernel_140/358127644.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gttab["Genotype"].replace(i,i.split("_")[0],inplace=True)

In [191]:
gttab.head()

   Genotype CAM_set  P-adj_highN subgenome
0         G     all     0.005853      both
8       2AB     all     0.004647      both
15       61     all     0.001912      both
18      1AB     all     0.001912      both
20        G     all     0.017427        Ya

In [192]:
gttab.rename(columns={"P-adj_highN":"P-adj"},inplace=True)
gttab.head()

/tmp/ipykernel_140/3219333157.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gttab.rename(columns={"P-adj_highN":"P-adj"},inplace=True)

   Genotype CAM_set     P-adj subgenome
0         G     all  0.005853      both
8       2AB     all  0.004647      both
15       61     all  0.001912      both
18      1AB     all  0.001912      both
20        G     all  0.017427        Ya

In [193]:
gttab = gttab[["Genotype","subgenome","CAM_set","P-adj"]]
gttab.head()

   Genotype subgenome CAM_set     P-adj
0         G      both     all  0.005853
8       2AB      both     all  0.004647
15       61      both     all  0.001912
18      1AB      both     all  0.001912
20        G        Ya     all  0.017427

In [194]:
gttab.sort_values(by="Genotype",ascending=True,inplace=True)

In [195]:
gttab.head()

   Genotype subgenome CAM_set     P-adj
17       18      both   light  0.041352
59      1AB        Ya   light  0.009964
18      1AB      both     all  0.001912
21      1AB      both   light  0.017427
56      1AB        Ya     all  0.029331

In [196]:
# save gttab
gttab.to_csv("./summarytable_genotype_camenrich_sig.csv",sep=",",header=True,index=False)

In [2]:
# Dec. 15
# reload camsig
camsig = pd.read_csv("./camenrich_tsgenes_sigp.txt",sep="\t",header="infer")
camsig.head()

,Group,P-value,Odds Ratio,P-adj,CAM_set,P-adj_highN,subgenome,group_type
0,Ya,0.000217,inf,0.000613,all,0.011533,Ya,overall_TSgenes
1,all,0.000408,5.454572,0.000613,all,0.017427,both,overall_TSgenes
2,1.0,0.000088,2.577190,0.001061,all,0.007789,both,ZTpeak_clustergroup
3,9.0,0.000832,2.279127,0.003746,all,0.028478,both,ZTpeak_clustergroup
4,5.0,0.000137,2.549830,0.001061,all,0.009290,both,ZTpeak_clustergroup

In [5]:
camsig["group_type"].unique()

array(['overall_TSgenes', 'ZTpeak_clustergroup', 'genotype_TSgenes',
       'individual_cluster'], dtype=object)

In [17]:
camsig[camsig["group_type"]=="overall_TSgenes"]

,Group,P-value,Odds Ratio,P-adj,CAM_set,P-adj_highN,subgenome,group_type
0,Ya,0.000217,inf,0.000613,all,0.011533,Ya,overall_TSgenes
1,all,0.000408,5.454572,0.000613,all,0.017427,both,overall_TSgenes

In [7]:
# make a summary table of the individual clusters
cres = camsig[camsig["group_type"]=="individual_cluster"]

In [8]:
cres.rename(columns={"Group":"ClusterID"},inplace=True)

/tmp/ipykernel_5985/4172504066.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cres.rename(columns={"Group":"ClusterID"},inplace=True)

In [9]:
cres.drop(["P-value","Odds Ratio","P-adj","group_type"],axis=1,inplace=True)
cres.rename(columns={"P-adj-highN":"P-adj"},inplace=True)

/tmp/ipykernel_5985/797454565.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cres.drop(["P-value","Odds Ratio","P-adj","group_type"],axis=1,inplace=True)
/tmp/ipykernel_5985/797454565.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cres.rename(columns={"P-adj-highN":"P-adj"},inplace=True)

In [10]:
cres.head()

   ClusterID CAM_set  P-adj_highN subgenome
15       G_1     all     0.035065      both
16      13_2     all     0.020587      both
17      51_6     all     0.004647      both
18      61_2     all     0.003066      both
19      61_5     all     0.031377      both

In [11]:
# split ClusterID column into Genotype and Cluster Number
gt = []
cnum = []
for i in list(cres["ClusterID"]):
    gt.append(i.split("_")[0])
    cnum.append(i.split("_")[1])
cres["Genotype"] = gt
cres["Cluster"] = cnum
cres.head()

/tmp/ipykernel_5985/3965179623.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cres["Genotype"] = gt
/tmp/ipykernel_5985/3965179623.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cres["Cluster"] = cnum

   ClusterID CAM_set  P-adj_highN subgenome Genotype Cluster
15       G_1     all     0.035065      both        G       1
16      13_2     all     0.020587      both       13       2
17      51_6     all     0.004647      both       51       6
18      61_2     all     0.003066      both       61       2
19      61_5     all     0.031377      both       61       5

In [12]:
cres = cres[["Genotype","Cluster","CAM_set","P-adj_highN"]]

In [13]:
cres.rename(columns={"P-adj_highN":"P-adj"},inplace=True)

In [14]:
cres.head()

   Genotype Cluster CAM_set     P-adj
15        G       1     all  0.035065
16       13       2     all  0.020587
17       51       6     all  0.004647
18       61       2     all  0.003066
19       61       5     all  0.031377

In [15]:
cres.to_csv("./summarytable_camenrich_sigclusters.csv",sep=",",header=True,index=False)